/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Cards4Links
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian3 = require("obsidian");

// src/cache-cleanup-modal.ts
var import_obsidian2 = require("obsidian");

// src/image-cache.ts
var import_obsidian = require("obsidian");
function extension(url) {
  const match = url.match(/\.(jpe?g|png|gif|webp|bmp|svg|ico)(\?|#|$)/i);
  return match ? match[1].toLowerCase() : "jpg";
}
function hashUrl(url) {
  return __async(this, null, function* () {
    const data = new TextEncoder().encode(url);
    const hash = yield crypto.subtle.digest("SHA-256", data);
    const hex = Array.from(new Uint8Array(hash.slice(0, 8))).map((b) => b.toString(16).padStart(2, "0")).join("");
    return `${hex}.${extension(url)}`;
  });
}
function downloadImage(url) {
  return __async(this, null, function* () {
    const res = yield (0, import_obsidian.requestUrl)(url);
    return res.arrayBuffer;
  });
}
function getCacheFolderPath(activeFile, location, folderName) {
  if (location === "note-relative" && activeFile) {
    const parent = activeFile.parent;
    return parent ? `${parent.path}/${folderName}` : folderName;
  }
  return folderName;
}
function ensureFolder(app, path) {
  return __async(this, null, function* () {
    const existing = app.vault.getFolderByPath(path);
    if (existing) return;
    yield app.vault.createFolder(path);
  });
}
var MANIFEST_FILE = "_manifest.json";
function getManifest(app, folder) {
  return __async(this, null, function* () {
    const file = app.vault.getAbstractFileByPath(`${folder}/${MANIFEST_FILE}`);
    if (!file || !(file instanceof import_obsidian.TFile)) {
      return { version: 1, files: [] };
    }
    try {
      const content = yield app.vault.read(file);
      return JSON.parse(content);
    } catch (e) {
      return { version: 1, files: [] };
    }
  });
}
function saveManifest(app, folder, manifest) {
  return __async(this, null, function* () {
    const path = `${folder}/${MANIFEST_FILE}`;
    const existing = app.vault.getAbstractFileByPath(path);
    const content = JSON.stringify(manifest, null, 2);
    if (existing && existing instanceof import_obsidian.TFile) {
      yield app.vault.modify(existing, content);
    } else {
      yield app.vault.create(path, content);
    }
  });
}
function addToManifest(app, folder, entry) {
  return __async(this, null, function* () {
    const manifest = yield getManifest(app, folder);
    const idx = manifest.files.findIndex((f) => f.filename === entry.filename);
    if (idx >= 0) {
      manifest.files[idx] = entry;
    } else {
      manifest.files.push(entry);
    }
    yield saveManifest(app, folder, manifest);
  });
}
function removeFromManifest(app, folder, filenames) {
  return __async(this, null, function* () {
    const manifest = yield getManifest(app, folder);
    manifest.files = manifest.files.filter(
      (f) => !filenames.includes(f.filename)
    );
    yield saveManifest(app, folder, manifest);
  });
}
function deleteFiles(app, folder, filenames) {
  return __async(this, null, function* () {
    for (const name of filenames) {
      if (name === MANIFEST_FILE) continue;
      const path = `${folder}/${name}`;
      const file = app.vault.getAbstractFileByPath(path);
      if (file) {
        yield app.vault.delete(file);
      }
    }
    yield removeFromManifest(app, folder, filenames);
  });
}
function resolveResourceUrl(app, localPath) {
  return __async(this, null, function* () {
    const file = app.vault.getAbstractFileByPath(localPath);
    if (!file || !(file instanceof import_obsidian.TFile)) return null;
    return app.vault.getResourcePath(file);
  });
}
function scanReferences(app) {
  return __async(this, null, function* () {
    const refs = /* @__PURE__ */ new Set();
    const files = app.vault.getMarkdownFiles();
    for (const file of files) {
      const content = yield app.vault.cachedRead(file);
      const regex = /imageLocal:\s*(\S+)/g;
      let match;
      while ((match = regex.exec(content)) !== null) {
        refs.add(match[1]);
      }
    }
    return refs;
  });
}
function isExpired(entry, ttlDays) {
  if (ttlDays <= 0) return false;
  const age = Date.now() - new Date(entry.cachedAt).getTime();
  return age > ttlDays * 864e5;
}

// src/cache-cleanup-modal.ts
function fmtSize(bytes) {
  if (bytes >= 1048576) return `${(bytes / 1048576).toFixed(1)} MB`;
  if (bytes >= 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${bytes} B`;
}
function fmtAge(iso) {
  const days = Math.floor(
    (Date.now() - new Date(iso).getTime()) / 864e5
  );
  if (days < 1) return "today";
  if (days === 1) return "1 day";
  if (days < 30) return `${days} days`;
  const months = Math.floor(days / 30);
  return months === 1 ? "1 month" : `${months} months`;
}
var CacheCleanupModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.rows = [];
    this.folder = "";
    this.loading = true;
  }
  onOpen() {
    return __async(this, null, function* () {
      const { contentEl } = this;
      contentEl.addClass("cards4links-modal");
      contentEl.empty();
      contentEl.createEl("h2", { text: "Cache Cleanup" });
      this.container = contentEl.createDiv();
      this.container.setText("Scanning cache\u2026");
      yield this.loadData();
      this.render();
    });
  }
  loadData() {
    return __async(this, null, function* () {
      this.folder = getCacheFolderPath(
        this.app.workspace.getActiveFile(),
        this.plugin.settings.cacheLocation,
        this.plugin.settings.cacheFolder
      );
      const manifest = yield getManifest(this.app, this.folder);
      const refs = yield scanReferences(this.app);
      const ttl = this.plugin.settings.cacheTTL;
      this.rows = manifest.files.map((entry) => ({
        entry,
        checked: false,
        referenced: refs.has(entry.filename) || refs.has(`${this.folder}/${entry.filename}`),
        expired: isExpired(entry, ttl)
      }));
      this.loading = false;
    });
  }
  render() {
    this.container.empty();
    if (this.loading) {
      this.container.setText("Scanning cache\u2026");
      return;
    }
    const totalSize = this.rows.reduce((s, r) => s + r.entry.size, 0);
    const expiredCount = this.rows.filter((r) => r.expired).length;
    const orphanCount = this.rows.filter((r) => !r.referenced).length;
    const summaryEl = this.container.createDiv({ cls: "cards4links-cache-summary" });
    summaryEl.createSpan({
      text: `${this.rows.length} files \u2014 ${fmtSize(totalSize)}`
    });
    if (expiredCount > 0) {
      summaryEl.createSpan({
        text: ` \u2014 ${expiredCount} expired`
      });
    }
    const actionsEl = this.container.createDiv({ cls: "cards4links-cache-actions" });
    actionsEl.createEl("button", { text: "Select all", cls: "clickable-icon" }).addEventListener("click", () => {
      this.rows.forEach((r) => r.checked = true);
      this.render();
    });
    if (expiredCount > 0) {
      actionsEl.createEl("button", { text: "Select expired", cls: "clickable-icon" }).addEventListener("click", () => {
        this.rows.forEach((r) => r.checked = r.expired);
        this.render();
      });
    }
    if (orphanCount > 0) {
      actionsEl.createEl("button", { text: "Select orphans", cls: "clickable-icon" }).addEventListener("click", () => {
        this.rows.forEach((r) => r.checked = !r.referenced);
        this.render();
      });
    }
    actionsEl.createEl("button", { text: "Deselect all", cls: "clickable-icon" }).addEventListener("click", () => {
      this.rows.forEach((r) => r.checked = false);
      this.render();
    });
    const table = this.container.createEl("table", { cls: "cards4links-cache-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "" });
    headerRow.createEl("th", { text: "File" });
    headerRow.createEl("th", { text: "Size" });
    headerRow.createEl("th", { text: "Age" });
    headerRow.createEl("th", { text: "" });
    const tbody = table.createEl("tbody");
    for (const row of this.rows) {
      const tr = tbody.createEl("tr");
      tr.addClass("cards4links-cache-row");
      const cbTd = tr.createEl("td");
      const cb = cbTd.createEl("input", { attr: { type: "checkbox" } });
      cb.checked = row.checked;
      cb.addEventListener("change", () => {
        row.checked = cb.checked;
      });
      tr.createEl("td", { text: row.entry.filename });
      tr.createEl("td", { text: fmtSize(row.entry.size) });
      tr.createEl("td", { text: fmtAge(row.entry.cachedAt) });
      const statusTd = tr.createEl("td");
      if (!row.referenced) {
        statusTd.createSpan({ text: "orphan", cls: "cards4links-cache-orphan" });
      } else if (row.expired) {
        statusTd.createSpan({ text: "expired", cls: "cards4links-cache-expired" });
      } else {
        statusTd.createSpan({ text: "ok", cls: "cards4links-cache-ok" });
      }
    }
    const deleteBtn = this.container.createEl("button", {
      cls: "mod-cta",
      text: "Delete selected"
    });
    deleteBtn.addEventListener("click", () => __async(this, null, function* () {
      const selected = this.rows.filter((r) => r.checked);
      if (selected.length === 0) {
        new import_obsidian2.Notice("No files selected");
        return;
      }
      const filenames = selected.map((r) => r.entry.filename);
      yield deleteFiles(this.app, this.folder, filenames);
      this.rows = this.rows.filter((r) => !r.checked);
      new import_obsidian2.Notice(`Deleted ${filenames.length} file(s)`);
      this.render();
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
function isThumbnailPosition(v) {
  return v === "right" || v === "left" || v === "none";
}
function isCardView(v) {
  return v === "card" || v === "compact" || v === "minimal";
}
function isCardTheme(v) {
  return v === "default" || v === "light" || v === "dark";
}
var DEFAULT_SETTINGS = {
  enhanceDefaultPaste: false,
  thumbnailPosition: "right",
  showInMenuItem: true,
  enableWatched: false,
  defaultView: "card",
  theme: "default",
  cacheImages: false,
  cacheFolder: "cards4links-cache",
  cacheLocation: "vault-absolute",
  cacheTTL: 30
};
var Cards4LinksSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Enhance default paste").setDesc(
      "Automatically fetch metadata when pasting a URL with the default paste command"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enhanceDefaultPaste).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.enhanceDefaultPaste = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian3.Setting(containerEl).setName("Thumbnail position").setDesc("Where to show the thumbnail image in the card").addDropdown(
      (dropdown) => dropdown.addOption("right", "Right").addOption("left", "Left").addOption("none", "No thumbnail").setValue(this.plugin.settings.thumbnailPosition).onChange((value) => __async(this, null, function* () {
        if (!isThumbnailPosition(value)) return;
        this.plugin.settings.thumbnailPosition = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian3.Setting(containerEl).setName("Show commands in menu item").setDesc("Add paste/enhance commands to the right-click context menu").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showInMenuItem).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showInMenuItem = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian3.Setting(containerEl).setName("Enable watched/read checkbox").setDesc(
      "Show a checkbox on cards to track watched (video) or read (article) status"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableWatched).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.enableWatched = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian3.Setting(containerEl).setName("Default card view").setDesc("Default view style for newly created cards").addDropdown(
      (dropdown) => dropdown.addOption("card", "Card").addOption("compact", "Compact").addOption("minimal", "Minimal").setValue(this.plugin.settings.defaultView).onChange((value) => __async(this, null, function* () {
        if (!isCardView(value)) return;
        this.plugin.settings.defaultView = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian3.Setting(containerEl).setName("Card theme").setDesc("Override card colors (default follows Obsidian theme)").addDropdown(
      (dropdown) => dropdown.addOption("default", "Default").addOption("light", "Light").addOption("dark", "Dark").setValue(this.plugin.settings.theme).onChange((value) => __async(this, null, function* () {
        if (!isCardTheme(value)) return;
        this.plugin.settings.theme = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian3.Setting(containerEl).setName("Cache images locally").setDesc("Download card images to the vault for offline access").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.cacheImages).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.cacheImages = value;
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
    if (this.plugin.settings.cacheImages) {
      new import_obsidian3.Setting(containerEl).setName("Cache storage").setDesc("Store images in a global vault folder or next to each note").addDropdown(
        (dropdown) => dropdown.addOption("vault-absolute", "Global folder").addOption("note-relative", "Per note").setValue(this.plugin.settings.cacheLocation).onChange((value) => __async(this, null, function* () {
          if (value !== "vault-absolute" && value !== "note-relative") return;
          this.plugin.settings.cacheLocation = value;
          yield this.plugin.saveSettings();
          this.display();
        }))
      );
      if (this.plugin.settings.cacheLocation === "vault-absolute") {
        new import_obsidian3.Setting(containerEl).setName("Cache folder name").setDesc("Folder path for cached images (vault root)").addText(
          (text) => text.setValue(this.plugin.settings.cacheFolder).onChange((value) => __async(this, null, function* () {
            this.plugin.settings.cacheFolder = value || "cards4links-cache";
            yield this.plugin.saveSettings();
          }))
        );
      }
      new import_obsidian3.Setting(containerEl).setName("Cache TTL").setDesc("How long before re-downloading a cached image").addDropdown(
        (dropdown) => dropdown.addOption("7", "7 days").addOption("30", "30 days").addOption("90", "90 days").addOption("180", "180 days").addOption("0", "Never expire").setValue(String(this.plugin.settings.cacheTTL)).onChange((value) => __async(this, null, function* () {
          this.plugin.settings.cacheTTL = parseInt(value);
          yield this.plugin.saveSettings();
        }))
      );
      new import_obsidian3.Setting(containerEl).setName("Manage cache").setDesc("View cache contents and clean up files").addButton(
        (btn) => btn.setButtonText("Manage cache\u2026").onClick(() => {
          const modal = new CacheCleanupModal(
            this.plugin.app,
            this.plugin
          );
          modal.open();
        })
      );
    }
  }
};

// src/card-generator.ts
var import_obsidian4 = require("obsidian");

// src/metadata-parser.ts
var MetadataParser = class {
  constructor(url, htmlText) {
    this.url = url;
    const parser = new DOMParser();
    this.htmlDoc = parser.parseFromString(htmlText, "text/html");
  }
  parse() {
    return __async(this, null, function* () {
      var _a, _b;
      const title = (_a = this.getTitle()) == null ? void 0 : _a.replace(/\r\n|\n|\r/g, "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').trim();
      if (!title) return;
      const description = (_b = this.getDescription()) == null ? void 0 : _b.replace(/\r\n|\n|\r/g, "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').trim();
      const { hostname } = new URL(this.url);
      const favicon = yield this.getFavicon();
      const image = yield this.getImage();
      return {
        url: this.url,
        title,
        description,
        host: hostname,
        favicon,
        image
      };
    });
  }
  getTitle() {
    var _a, _b, _c;
    const ogTitle = (_a = this.htmlDoc.querySelector("meta[property='og:title']")) == null ? void 0 : _a.getAttr("content");
    if (ogTitle) return ogTitle;
    return (_c = (_b = this.htmlDoc.querySelector("title")) == null ? void 0 : _b.textContent) != null ? _c : void 0;
  }
  getDescription() {
    var _a, _b, _c;
    const ogDesc = (_a = this.htmlDoc.querySelector("meta[property='og:description']")) == null ? void 0 : _a.getAttr("content");
    if (ogDesc) return ogDesc;
    return (_c = (_b = this.htmlDoc.querySelector("meta[name='description']")) == null ? void 0 : _b.getAttr("content")) != null ? _c : void 0;
  }
  getFavicon() {
    return __async(this, null, function* () {
      var _a;
      const href = (_a = this.htmlDoc.querySelector("link[rel='icon']")) == null ? void 0 : _a.getAttr("href");
      if (href) return this.resolveUrlDual(href);
      return void 0;
    });
  }
  getImage() {
    return __async(this, null, function* () {
      var _a;
      const content = (_a = this.htmlDoc.querySelector("meta[property='og:image']")) == null ? void 0 : _a.getAttr("content");
      if (content) return this.resolveUrlDual(content);
      return void 0;
    });
  }
  resolveUrl(imageUrl) {
    if (imageUrl.startsWith("//")) {
      return `https:${imageUrl}`;
    }
    if (imageUrl.startsWith("/")) {
      const { hostname } = new URL(this.url);
      return `https://${hostname}${imageUrl}`;
    }
    return imageUrl;
  }
  resolveUrlDual(url) {
    if (!url.startsWith("//")) return Promise.resolve(this.resolveUrl(url));
    const httpsUrl = `https:${url}`;
    const httpUrl = `http:${url}`;
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => resolve(httpsUrl);
      img.onerror = () => {
        const img2 = new Image();
        img2.onload = () => resolve(httpUrl);
        img2.onerror = () => resolve(httpsUrl);
        img2.src = httpUrl;
      };
      img.src = httpsUrl;
    });
  }
};

// src/utils.ts
var urlRegex = /^(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})$/i;
var lineUrlRegex = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
var linkRegex = /^\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)$/i;
var linkLineRegex = /\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)/gi;
var imageRegex = /\.(gif|jpe?g|tiff?|png|webp|bmp|tga|psd|ai)$/i;
function isUrl(text) {
  return urlRegex.test(text);
}
function isImage(text) {
  return imageRegex.test(text);
}
function isLinkedUrl(text) {
  return linkRegex.test(text);
}
function extractUrlFromLink(link) {
  const match = linkRegex.exec(link);
  if (!match || match.length < 3) return "";
  return match[2];
}

// src/editor-extensions.ts
var EditorExtensions = class {
  static getSelectedText(editor) {
    if (!editor.somethingSelected()) {
      const bounds = this.getWordBoundaries(editor);
      editor.setSelection(bounds.start, bounds.end);
    }
    return editor.getSelection();
  }
  static posFromIndex(content, index) {
    const substr = content.substring(0, index);
    let line = 0;
    let offset = -1;
    let r = -1;
    for (; (r = substr.indexOf("\n", r + 1)) !== -1; line++, offset = r) ;
    offset += 1;
    const ch = index - offset;
    return { line, ch };
  }
  static isCursorInRange(cursor, match) {
    var _a;
    const start = (_a = match.index) != null ? _a : 0;
    const end = start + match[0].length;
    return start <= cursor.ch && cursor.ch <= end;
  }
  static getWordBoundaries(editor) {
    var _a, _b;
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    for (const match of lineText.matchAll(linkLineRegex)) {
      if (this.isCursorInRange(cursor, match)) {
        const startCh = (_a = match.index) != null ? _a : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    for (const match of lineText.matchAll(lineUrlRegex)) {
      if (this.isCursorInRange(cursor, match)) {
        const startCh = (_b = match.index) != null ? _b : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    return { start: cursor, end: cursor };
  }
};

// src/card-generator.ts
var CardGenerator = class {
  constructor(editor, defaultView = "card", cacheImages = false, cacheFolder = "cards4links-cache", cacheLocation = "vault-absolute", app) {
    this.editor = editor;
    this.defaultView = defaultView;
    this.cacheImages = cacheImages;
    this.cacheFolder = cacheFolder;
    this.cacheLocation = cacheLocation;
    this.app = app;
  }
  convert(url) {
    return __async(this, null, function* () {
      const selectedText = this.editor.getSelection();
      const placeholderId = this.randomId();
      const placeholder = `[Fetching Data#${placeholderId}](${url})`;
      this.editor.replaceSelection(placeholder);
      new import_obsidian4.Notice("Cards4Links: fetching metadata...");
      const metadata = yield this.fetchMetadata(url);
      if (metadata && this.cacheImages && metadata.image && this.app) {
        yield this.cacheImage(metadata);
      }
      const text = this.editor.getValue();
      const start = text.indexOf(placeholder);
      if (start < 0) {
        console.log(
          `Could not find placeholder "${placeholder}" in editor, bailing out; url ${url}`
        );
        return;
      }
      const end = start + placeholder.length;
      const startPos = EditorExtensions.posFromIndex(text, start);
      const endPos = EditorExtensions.posFromIndex(text, end);
      if (!metadata) {
        new import_obsidian4.Notice("Cards4Links: couldn't fetch link metadata");
        this.editor.replaceRange(selectedText || url, startPos, endPos);
        return;
      }
      this.editor.replaceRange(this.generateCodeBlock(metadata), startPos, endPos);
    });
  }
  generateCodeBlock(md) {
    const lines = ["\n```cardlink"];
    lines.push(`url: ${md.url}`);
    lines.push(`title: "${md.title}"`);
    if (md.description) lines.push(`description: "${md.description}"`);
    if (md.host) lines.push(`host: ${md.host}`);
    if (md.favicon) lines.push(`favicon: ${md.favicon}`);
    if (md.image) lines.push(`image: ${md.image}`);
    if (md.imageLocal) lines.push(`imageLocal: ${md.imageLocal}`);
    lines.push(`watched: false`);
    lines.push(`view: ${this.defaultView}`);
    lines.push("```\n");
    return lines.join("\n");
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      try {
        const res = yield (0, import_obsidian4.requestUrl)({ url });
        if (res.status !== 200) {
          console.log(`Cards4Links: bad response status ${res.status}`);
          return void 0;
        }
        const parser = new MetadataParser(url, res.text);
        return yield parser.parse();
      } catch (e) {
        console.log("Cards4Links fetch error:", e);
        return void 0;
      }
    });
  }
  cacheImage(metadata) {
    return __async(this, null, function* () {
      try {
        const activeFile = this.app.workspace.getActiveFile();
        const folder = getCacheFolderPath(
          activeFile,
          this.cacheLocation,
          this.cacheFolder
        );
        yield ensureFolder(this.app, folder);
        const filename = yield hashUrl(metadata.image);
        const existing = this.app.vault.getAbstractFileByPath(
          `${folder}/${filename}`
        );
        if (!existing) {
          const buffer = yield downloadImage(metadata.image);
          yield this.app.vault.createBinary(`${folder}/${filename}`, buffer);
        }
        const file = this.app.vault.getAbstractFileByPath(
          `${folder}/${filename}`
        );
        yield addToManifest(this.app, folder, {
          filename,
          originalUrl: metadata.image,
          cachedAt: (/* @__PURE__ */ new Date()).toISOString(),
          size: file && file instanceof import_obsidian4.TFile ? file.stat.size : 0
        });
        metadata.imageLocal = `${folder}/${filename}`;
      } catch (e) {
        console.log("Cards4Links: failed to cache image", e);
      }
    });
  }
  randomId() {
    const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
    let result = "";
    for (let i = 0; i < 4; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }
};

// src/card-processor.ts
var import_obsidian5 = require("obsidian");
function createSvgIcon(viewBox, size, ...elements) {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", viewBox);
  svg.setAttribute("width", String(size));
  svg.setAttribute("height", String(size));
  for (const [tag, attrs] of elements) {
    const el = document.createElementNS("http://www.w3.org/2000/svg", tag);
    for (const [key, val] of Object.entries(attrs)) {
      el.setAttribute(key, val);
    }
    svg.appendChild(el);
  }
  return svg;
}
function detectContentType(host) {
  if (!host) return "article";
  const videoHosts = [
    "youtube.com",
    "youtu.be",
    "vimeo.com",
    "twitch.tv",
    "dailymotion.com",
    "kick.com",
    "facebook.com"
  ];
  return videoHosts.some((h) => host.includes(h)) ? "video" : "article";
}
var YamlParseError = class extends Error {
  constructor(msg) {
    super(msg);
    this.name = "YamlParseError";
  }
};
var NoRequiredParamsError = class extends Error {
  constructor(msg) {
    super(msg);
    this.name = "NoRequiredParamsError";
  }
};
var CardProcessor = class {
  constructor(app, thumbnailPosition = "right", defaultView = "card", theme = "default", cacheImages = false, cacheFolder = "cards4links-cache", cacheLocation = "vault-absolute", cacheTTL = 30) {
    this.app = app;
    this.thumbnailPosition = thumbnailPosition;
    this.defaultView = defaultView;
    this.theme = theme;
    this.cacheImages = cacheImages;
    this.cacheFolder = cacheFolder;
    this.cacheLocation = cacheLocation;
    this.cacheTTL = cacheTTL;
    this.source = "";
    this.sections = [];
  }
  run(source, el) {
    this.source = source;
    const raw = source.split(/\n-{3,}\n/).map((s) => s.trim());
    this.sections = raw.length > 1 ? raw : [source];
    if (this.sections.length <= 1) {
      try {
        const data = this.parseYaml(source);
        this.renderCard(el, data, source, 0, false);
      } catch (error) {
        el.appendChild(this.renderError(error));
      }
    } else {
      const group = el.createDiv({ cls: "cards4links-group" });
      for (let i = 0; i < this.sections.length; i++) {
        try {
          const data = this.parseYaml(this.sections[i]);
          this.renderCard(group, data, this.sections[i], i, true);
        } catch (error) {
          group.appendChild(this.renderError(error));
        }
      }
    }
  }
  parseYaml(source) {
    var _a;
    let yaml;
    let indent = 0;
    const normalized = source.split(/\r?\n|\r|\n/g).map(
      (line) => line.replace(/^\t+/g, (tabs) => {
        if (indent === 0) indent = tabs.length;
        return " ".repeat(tabs.length);
      })
    ).join("\n");
    try {
      yaml = (0, import_obsidian5.parseYaml)(normalized);
    } catch (error) {
      console.log("Cards4Links YAML parse error:", error);
      throw new YamlParseError(
        "Failed to parse YAML. Check debug console for details."
      );
    }
    if (!yaml || !yaml.url || !yaml.title) {
      throw new NoRequiredParamsError(
        "Required params [url, title] not found."
      );
    }
    return {
      url: yaml.url,
      title: yaml.title,
      description: yaml.description,
      host: yaml.host,
      favicon: yaml.favicon,
      image: yaml.image,
      watched: yaml.watched === true,
      view: (_a = yaml.view) != null ? _a : "card",
      contentType: detectContentType(yaml.host)
    };
  }
  renderCard(parentEl, data, sectionSource, cardIndex, isGroup) {
    const view = isGroup ? "card" : data.view || "card";
    const needsUpgrade = !/^view:/m.test(sectionSource);
    const actionsBar = createDiv({ cls: "cards4links-actions-bar" });
    if (!isGroup) {
      actionsBar.classList.add("cards4links-actions-bar-float");
    }
    if (needsUpgrade) {
      const upgradeBtn = actionsBar.createEl("button", {
        cls: "cards4links-upgrade-btn clickable-icon",
        attr: { "aria-label": "Add view field to card" }
      });
      upgradeBtn.appendChild(
        createSvgIcon(
          "0 0 24 24",
          14,
          ["path", { d: "M5 10l7-7 7 7", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["path", { d: "M12 3v18", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
        )
      );
      upgradeBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        container.dataset.view = isGroup ? "card" : this.defaultView;
        const oldSource = this.source;
        const newSections = [...this.sections];
        newSections[cardIndex] = newSections[cardIndex] + `
view: ${isGroup ? "card" : this.defaultView}`;
        const newSource = newSections.join("\n---\n");
        this.replaceBlock(oldSource, newSource);
        this.sections = newSections;
        this.source = newSource;
        upgradeBtn.remove();
      });
    }
    if (!isGroup) {
      const viewCycle = ["card", "compact", "minimal"];
      const viewBtn = actionsBar.createEl("button", {
        cls: "cards4links-view-btn clickable-icon",
        attr: { "aria-label": `View: ${view}` }
      });
      viewBtn.appendChild(
        createSvgIcon(
          "0 0 24 24",
          14,
          ["rect", { x: "3", y: "3", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["rect", { x: "13", y: "3", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["rect", { x: "3", y: "13", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["rect", { x: "13", y: "13", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
        )
      );
      viewBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const currentView = container.dataset.view || "card";
        const next = viewCycle[(viewCycle.indexOf(currentView) + 1) % viewCycle.length];
        container.dataset.view = next;
        this.updateCardBlock(cardIndex, "view", next);
      });
    }
    const label = data.contentType === "video" ? "Watched" : "Read";
    const watchToggleBtn = actionsBar.createEl("button", {
      cls: "cards4links-watch-toggle clickable-icon",
      attr: {
        "aria-label": data.watched ? "Mark as Unread" : `Mark as ${label}`
      }
    });
    const checkedSvg = createSvgIcon(
      "0 0 24 24",
      14,
      ["circle", { cx: "12", cy: "12", r: "10", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
      ["path", { d: "M8 12l3 3 5-5", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
    );
    const uncheckedSvg = createSvgIcon(
      "0 0 24 24",
      14,
      ["circle", { cx: "12", cy: "12", r: "10", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
    );
    watchToggleBtn.appendChild(data.watched ? checkedSvg.cloneNode(true) : uncheckedSvg.cloneNode(true));
    watchToggleBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const currentlyWatched = container.dataset.watched === "true";
      const newWatched = !currentlyWatched;
      container.dataset.watched = newWatched ? "true" : "false";
      watchToggleBtn.empty();
      watchToggleBtn.appendChild(newWatched ? checkedSvg.cloneNode(true) : uncheckedSvg.cloneNode(true));
      watchToggleBtn.setAttr(
        "aria-label",
        newWatched ? "Mark as Unread" : `Mark as ${label}`
      );
      this.updateCardBlock(cardIndex, "watched", newWatched);
    });
    const container = createDiv({
      cls: "cards4links-container",
      attr: {
        "data-thumbnail": this.thumbnailPosition,
        "data-view": view,
        "data-watched": data.watched ? "true" : "false",
        "data-theme": this.theme
      }
    });
    const card = container.createEl("a", {
      cls: "cards4links-card",
      attr: { href: data.url }
    });
    const main = card.createDiv({ cls: "cards4links-main" });
    const titleRow = main.createDiv({ cls: "cards4links-title-row" });
    titleRow.createSpan({
      cls: "cards4links-title-text",
      text: data.title
    });
    if (data.description) {
      main.createDiv({
        cls: "cards4links-description",
        text: data.description
      });
    } else {
      this.createDescriptionPlaceholder(main, cardIndex);
    }
    const hostRow = main.createDiv({ cls: "cards4links-host" });
    if (data.favicon) {
      hostRow.createEl("img", {
        cls: "cards4links-favicon",
        attr: { src: data.favicon }
      });
    }
    if (data.host) {
      hostRow.createSpan({ text: data.host });
    }
    if (data.image) {
      this.renderImage(card, data, cardIndex);
    } else {
      this.createImagePlaceholder(card, cardIndex);
    }
    const copyBtn = container.createEl("button", {
      cls: "cards4links-copy-url clickable-icon",
      attr: { "aria-label": `Copy URL
${data.url}` }
    });
    copyBtn.appendChild(
      createSvgIcon(
        "0 0 24 24",
        16,
        ["path", { fill: "currentColor", d: "M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z" }]
      )
    );
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void navigator.clipboard.writeText(data.url);
      new import_obsidian5.Notice("URL copied to clipboard");
    });
    if (isGroup) {
      const wrapper = createDiv({ cls: "cards4links-card-wrapper" });
      wrapper.appendChild(actionsBar);
      wrapper.appendChild(container);
      parentEl.appendChild(wrapper);
    } else {
      parentEl.appendChild(actionsBar);
      parentEl.appendChild(container);
    }
  }
  renderImage(card, data, cardIndex) {
    const tryLocal = data.imageLocal && this.cacheImages;
    const doRender = (src) => {
      const img = card.createEl("img", {
        cls: "cards4links-thumbnail",
        attr: { src, draggable: "false" }
      });
      img.addEventListener("error", () => {
        if (tryLocal && data.image) {
          img.remove();
          doRender(data.image);
          return;
        }
        img.remove();
        this.createImagePlaceholder(card, cardIndex, data.image);
      });
    };
    if (tryLocal) {
      void resolveResourceUrl(this.app, data.imageLocal).then((url) => {
        if (url) {
          doRender(url);
          void this.checkTtl(data);
        } else if (data.image) {
          doRender(data.image);
        } else {
          this.createImagePlaceholder(card, cardIndex);
        }
      });
    } else if (data.image) {
      doRender(data.image);
    }
  }
  checkTtl(data) {
    return __async(this, null, function* () {
      if (!data.imageLocal || this.cacheTTL <= 0 || !data.image) return;
      const folder = getCacheFolderPath(
        this.app.workspace.getActiveFile(),
        this.cacheLocation,
        this.cacheFolder
      );
      const manifest = yield getManifest(this.app, folder);
      const pathParts = data.imageLocal.split("/");
      const filename = pathParts[pathParts.length - 1];
      const entry = manifest.files.find((f) => f.filename === filename);
      if (!entry) return;
      if (!isExpired(entry, this.cacheTTL)) return;
      try {
        const buffer = yield downloadImage(data.image);
        const file = this.app.vault.getAbstractFileByPath(data.imageLocal);
        if (file instanceof import_obsidian5.TFile) {
          yield this.app.vault.modifyBinary(file, buffer);
        } else {
          yield ensureFolder(this.app, folder);
          yield this.app.vault.createBinary(data.imageLocal, buffer);
        }
        const tf = this.app.vault.getAbstractFileByPath(data.imageLocal);
        yield addToManifest(this.app, folder, {
          filename,
          originalUrl: data.image,
          cachedAt: (/* @__PURE__ */ new Date()).toISOString(),
          size: tf instanceof import_obsidian5.TFile ? tf.stat.size : 0
        });
      } catch (e) {
        console.log("Cards4Links: TTL refresh failed", e);
      }
    });
  }
  createImagePlaceholder(cardEl, cardIndex, currentImageUrl) {
    const placeholder = cardEl.createDiv({ cls: "cards4links-img-placeholder" });
    const svgContainer = placeholder.createDiv({ cls: "cards4links-img-placeholder-icon" });
    svgContainer.appendChild(
      createSvgIcon(
        "0 0 24 24",
        22,
        ["rect", { x: "2", y: "2", width: "20", height: "20", rx: "2", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
        ["path", { d: "M21 15l-5-5L5 21", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }],
        ["path", { d: "M17 6h6M20 3v6", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }]
      )
    );
    placeholder.createSpan({
      cls: "cards4links-img-placeholder-text",
      text: "Set image"
    });
    placeholder.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const modal = new ImagePickerModal(
        this.app,
        currentImageUrl,
        (newUrl) => {
          this.updateCardBlock(cardIndex, "image", newUrl);
        }
      );
      modal.open();
    });
  }
  createDescriptionPlaceholder(main, cardIndex) {
    const placeholder = main.createDiv({ cls: "cards4links-description-placeholder" });
    placeholder.appendChild(
      createSvgIcon(
        "0 0 24 24",
        12,
        ["path", { d: "M17 3a2.828 2.828 0 114 4L7.5 20.5 2 22l1.5-5.5L17 3z", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }]
      )
    );
    placeholder.createSpan({
      text: "Add description"
    });
    placeholder.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const modal = new DescriptionInputModal(
        this.app,
        (value) => {
          this.updateCardBlock(cardIndex, "description", value);
        }
      );
      modal.open();
    });
  }
  updateCardBlock(cardIndex, field, value) {
    const section = this.sections[cardIndex];
    const fieldRegex = new RegExp(`^${field}:.*$`, "m");
    const newSection = fieldRegex.test(section) ? section.replace(fieldRegex, `${field}: ${value}`) : section + `
${field}: ${value}`;
    const newSections = [...this.sections];
    newSections[cardIndex] = newSection;
    const newSource = newSections.join("\n---\n");
    const oldSource = this.source;
    this.replaceBlock(oldSource, newSource);
    this.sections = newSections;
    this.source = newSource;
  }
  replaceBlock(oldSource, newSource) {
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (!markdownView) {
      console.log("Cards4Links: no active MarkdownView");
      new import_obsidian5.Notice("Cards4Links: cannot edit in Reading view");
      return;
    }
    const editor = markdownView.editor;
    if (!editor) {
      console.log("Cards4Links: no editor available");
      return;
    }
    const text = editor.getValue();
    const blockRegex = /```cardlink\s*\n([\s\S]*?)```/g;
    let match;
    while ((match = blockRegex.exec(text)) !== null) {
      const blockContent = match[1];
      if (blockContent.replace(/\r\n/g, "\n").trimEnd() !== oldSource.replace(/\r\n/g, "\n").trimEnd()) continue;
      const lines = blockContent.split("\n");
      const hasPrefix = lines.some((l) => l.trim() && l.startsWith("> "));
      const finalContent = hasPrefix ? newSource.split("\n").map((l) => "> " + l).join("\n") : newSource;
      const startPos = EditorExtensions.posFromIndex(text, match.index);
      const endPos = EditorExtensions.posFromIndex(
        text,
        match.index + match[0].length
      );
      try {
        editor.replaceRange(
          `\`\`\`cardlink
${finalContent}
\`\`\``,
          startPos,
          endPos
        );
      } catch (e) {
        console.log("Cards4Links: failed to update code block", e);
        new import_obsidian5.Notice("Cards4Links: error updating card state");
      }
      break;
    }
  }
  renderError(error) {
    const container = createDiv({ cls: "cards4links-error" });
    container.setText(`cardlink error: ${error.message}`);
    return container;
  }
};
var ImagePickerModal = class extends import_obsidian5.Modal {
  constructor(app, currentUrl, onSubmit) {
    super(app);
    this.currentUrl = currentUrl != null ? currentUrl : "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("cards4links-modal");
    contentEl.createEl("h2", { text: "Set card image" });
    let imageUrl = this.currentUrl;
    let textInput;
    new import_obsidian5.Setting(contentEl).setName("Image URL").setDesc("Enter or paste a URL for the card image").addText((text) => {
      text.setValue(imageUrl);
      text.onChange((value) => {
        imageUrl = value;
      });
      text.inputEl.focus();
      text.inputEl.select();
      textInput = text.inputEl;
    }).addExtraButton((btn) => {
      btn.setIcon("clipboard");
      btn.setTooltip("Paste from clipboard");
      btn.onClick(() => __async(this, null, function* () {
        try {
          const clipboardText = yield navigator.clipboard.readText();
          if (clipboardText) {
            imageUrl = clipboardText;
            textInput.value = clipboardText;
          }
        } catch (e) {
        }
      }));
    });
    new import_obsidian5.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Save");
      btn.setCta();
      btn.onClick(() => {
        const url = imageUrl.trim();
        if (!url) return;
        const img = new Image();
        img.onload = () => {
          this.onSubmit(url);
          this.close();
        };
        img.onerror = () => {
          new import_obsidian5.Notice("Failed to load image. Please try a different URL.");
        };
        img.src = url;
      });
    }).addButton((btn) => {
      btn.setButtonText("Cancel");
      btn.onClick(() => {
        this.close();
      });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var DescriptionInputModal = class extends import_obsidian5.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("cards4links-modal");
    contentEl.createEl("h2", { text: "Set card description" });
    let description = "";
    new import_obsidian5.Setting(contentEl).setName("Description").addTextArea((text) => {
      text.setValue(description);
      text.onChange((value) => {
        description = value;
      });
      text.inputEl.rows = 4;
      text.inputEl.focus();
    });
    new import_obsidian5.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Save");
      btn.setCta();
      btn.onClick(() => {
        this.onSubmit(description);
        this.close();
      });
    }).addButton((btn) => {
      btn.setButtonText("Cancel");
      btn.onClick(() => {
        this.close();
      });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var Cards4Links = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.onPaste = (evt, editor) => __async(this, null, function* () {
      if (!this.settings.enhanceDefaultPaste) return;
      if (!navigator.onLine) return;
      if (!evt.clipboardData) return;
      if (evt.clipboardData.files.length > 0) return;
      const clipboardText = evt.clipboardData.getData("text/plain");
      if (!clipboardText) return;
      if (!isUrl(clipboardText) || isImage(clipboardText)) return;
      evt.stopPropagation();
      evt.preventDefault();
      const generator = this.makeGenerator(editor);
      yield generator.convert(clipboardText);
    });
    this.onEditorMenu = (menu) => {
      if (!this.settings.showInMenuItem) return;
      menu.addItem((item) => {
        item.setTitle("Paste URL and enhance to card link").setIcon("paste").onClick(() => __async(this, null, function* () {
          const editor = this.getEditor();
          if (!editor) return;
          yield this.manualPasteAndEnhance(editor);
        }));
      });
      if (!navigator.onLine) return;
      menu.addItem((item) => {
        item.setTitle("Enhance selected URL to card link").setIcon("link").onClick(() => {
          const editor = this.getEditor();
          if (!editor) return;
          void this.enhanceSelected(editor);
        });
      });
    };
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.registerMarkdownCodeBlockProcessor("cardlink", (source, el) => {
        const processor = new CardProcessor(
          this.app,
          this.settings.thumbnailPosition,
          this.settings.defaultView,
          this.settings.theme,
          this.settings.cacheImages,
          this.settings.cacheFolder,
          this.settings.cacheLocation,
          this.settings.cacheTTL
        );
        processor.run(source, el);
      });
      this.addCommand({
        id: "paste-and-enhance",
        name: "Paste URL and enhance to card link",
        editorCallback: (editor) => __async(this, null, function* () {
          yield this.manualPasteAndEnhance(editor);
        }),
        hotkeys: []
      });
      this.addCommand({
        id: "upgrade-old-cards",
        name: "Add view field to old cardlink cards",
        editorCallback: (editor) => {
          this.upgradeOldCards(editor);
        }
      });
      this.addCommand({
        id: "enhance-selected-url",
        name: "Enhance selected URL to card link",
        editorCheckCallback: (checking, editor) => {
          if (!navigator.onLine) return false;
          if (checking) return true;
          void this.enhanceSelected(editor);
          return;
        },
        hotkeys: [{ modifiers: ["Mod", "Shift"], key: "e" }]
      });
      this.addCommand({
        id: "open-settings",
        name: "Open plugin settings",
        hotkeys: [{ modifiers: ["Mod", "Shift"], key: "," }],
        callback: () => {
          const setting = this.app.setting;
          setting.open();
          setting.openTabById("cards-for-links");
        }
      });
      this.registerEvent(
        this.app.workspace.on("editor-paste", this.onPaste)
      );
      this.registerEvent(
        this.app.workspace.on("editor-menu", this.onEditorMenu)
      );
      this.addSettingTab(new Cards4LinksSettingTab(this.app, this));
    });
  }
  enhanceSelected(editor) {
    return __async(this, null, function* () {
      const selected = (EditorExtensions.getSelectedText(editor) || "").trim();
      const generator = this.makeGenerator(editor);
      for (const line of selected.split(/[\n ]/)) {
        if (isUrl(line)) {
          yield generator.convert(line);
        } else if (isLinkedUrl(line)) {
          const url = extractUrlFromLink(line);
          if (url) yield generator.convert(url);
        }
      }
    });
  }
  manualPasteAndEnhance(editor) {
    return __async(this, null, function* () {
      const clipboardText = yield navigator.clipboard.readText();
      if (!clipboardText) return;
      if (!navigator.onLine) {
        editor.replaceSelection(clipboardText);
        return;
      }
      if (!isUrl(clipboardText) || isImage(clipboardText)) {
        editor.replaceSelection(clipboardText);
        return;
      }
      const generator = this.makeGenerator(editor);
      yield generator.convert(clipboardText);
    });
  }
  upgradeOldCards(editor) {
    const text = editor.getValue();
    const blockRegex = /```cardlink\n([\s\S]*?)```/g;
    const replacements = [];
    let match;
    while ((match = blockRegex.exec(text)) !== null) {
      const blockContent = match[1].replace(/\r/g, "");
      if (/^view:/m.test(blockContent)) continue;
      const newContent = blockContent + (blockContent.endsWith("\n") ? "" : "\n") + `view: ${this.settings.defaultView}`;
      const startPos = EditorExtensions.posFromIndex(text, match.index);
      const endPos = EditorExtensions.posFromIndex(
        text,
        match.index + match[0].length
      );
      replacements.push({
        start: startPos,
        end: endPos,
        content: `\`\`\`cardlink
${newContent}\`\`\``
      });
    }
    if (replacements.length === 0) {
      new import_obsidian6.Notice("Cards4Links: no old cards found");
      return;
    }
    replacements.reverse();
    for (const r of replacements) {
      editor.replaceRange(r.content, r.start, r.end);
    }
    new import_obsidian6.Notice(`Cards4Links: updated ${replacements.length} card(s)`);
  }
  getEditor() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    return view == null ? void 0 : view.editor;
  }
  makeGenerator(editor) {
    return new CardGenerator(
      editor,
      this.settings.defaultView,
      this.settings.cacheImages,
      this.settings.cacheFolder,
      this.settings.cacheLocation,
      this.app
    );
  }
  loadSettings() {
    return __async(this, null, function* () {
      const data = yield this.loadData();
      this.settings = Object.assign(
        {},
        DEFAULT_SETTINGS,
        data
      );
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
