/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Cards4Links
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
function isThumbnailPosition(v) {
  return v === "right" || v === "left" || v === "none";
}
function isCardView(v) {
  return v === "card" || v === "compact" || v === "minimal";
}
var DEFAULT_SETTINGS = {
  enhanceDefaultPaste: false,
  thumbnailPosition: "right",
  showInMenuItem: true,
  enableWatched: false,
  defaultView: "card"
};
var Cards4LinksSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enhance default paste").setDesc(
      "Automatically fetch metadata when pasting a URL with the default paste command"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enhanceDefaultPaste).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.enhanceDefaultPaste = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Thumbnail position").setDesc("Where to show the thumbnail image in the card").addDropdown(
      (dropdown) => dropdown.addOption("right", "Right").addOption("left", "Left").addOption("none", "No thumbnail").setValue(this.plugin.settings.thumbnailPosition).onChange((value) => __async(this, null, function* () {
        if (!isThumbnailPosition(value)) return;
        this.plugin.settings.thumbnailPosition = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Show commands in menu item").setDesc("Add paste/enhance commands to the right-click context menu").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showInMenuItem).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showInMenuItem = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Enable watched/read checkbox").setDesc(
      "Show a checkbox on cards to track watched (video) or read (article) status"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableWatched).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.enableWatched = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian.Setting(containerEl).setName("Default card view").setDesc("Default view style for newly created cards").addDropdown(
      (dropdown) => dropdown.addOption("card", "Card").addOption("compact", "Compact").addOption("minimal", "Minimal").setValue(this.plugin.settings.defaultView).onChange((value) => __async(this, null, function* () {
        if (!isCardView(value)) return;
        this.plugin.settings.defaultView = value;
        yield this.plugin.saveSettings();
      }))
    );
  }
};

// src/card-generator.ts
var import_obsidian2 = require("obsidian");

// src/metadata-parser.ts
var MetadataParser = class {
  constructor(url, htmlText) {
    this.url = url;
    const parser = new DOMParser();
    this.htmlDoc = parser.parseFromString(htmlText, "text/html");
  }
  parse() {
    return __async(this, null, function* () {
      var _a, _b;
      const title = (_a = this.getTitle()) == null ? void 0 : _a.replace(/\r\n|\n|\r/g, "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').trim();
      if (!title) return;
      const description = (_b = this.getDescription()) == null ? void 0 : _b.replace(/\r\n|\n|\r/g, "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').trim();
      const { hostname } = new URL(this.url);
      const favicon = yield this.getFavicon();
      const image = yield this.getImage();
      return {
        url: this.url,
        title,
        description,
        host: hostname,
        favicon,
        image
      };
    });
  }
  getTitle() {
    var _a, _b, _c;
    const ogTitle = (_a = this.htmlDoc.querySelector("meta[property='og:title']")) == null ? void 0 : _a.getAttr("content");
    if (ogTitle) return ogTitle;
    return (_c = (_b = this.htmlDoc.querySelector("title")) == null ? void 0 : _b.textContent) != null ? _c : void 0;
  }
  getDescription() {
    var _a, _b, _c;
    const ogDesc = (_a = this.htmlDoc.querySelector("meta[property='og:description']")) == null ? void 0 : _a.getAttr("content");
    if (ogDesc) return ogDesc;
    return (_c = (_b = this.htmlDoc.querySelector("meta[name='description']")) == null ? void 0 : _b.getAttr("content")) != null ? _c : void 0;
  }
  getFavicon() {
    return __async(this, null, function* () {
      var _a;
      const href = (_a = this.htmlDoc.querySelector("link[rel='icon']")) == null ? void 0 : _a.getAttr("href");
      if (href) return this.resolveUrlDual(href);
      return void 0;
    });
  }
  getImage() {
    return __async(this, null, function* () {
      var _a;
      const content = (_a = this.htmlDoc.querySelector("meta[property='og:image']")) == null ? void 0 : _a.getAttr("content");
      if (content) return this.resolveUrlDual(content);
      return void 0;
    });
  }
  resolveUrl(imageUrl) {
    if (imageUrl.startsWith("//")) {
      return `https:${imageUrl}`;
    }
    if (imageUrl.startsWith("/")) {
      const { hostname } = new URL(this.url);
      return `https://${hostname}${imageUrl}`;
    }
    return imageUrl;
  }
  resolveUrlDual(url) {
    if (!url.startsWith("//")) return Promise.resolve(this.resolveUrl(url));
    const httpsUrl = `https:${url}`;
    const httpUrl = `http:${url}`;
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => resolve(httpsUrl);
      img.onerror = () => {
        const img2 = new Image();
        img2.onload = () => resolve(httpUrl);
        img2.onerror = () => resolve(httpsUrl);
        img2.src = httpUrl;
      };
      img.src = httpsUrl;
    });
  }
};

// src/utils.ts
var urlRegex = /^(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})$/i;
var lineUrlRegex = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
var linkRegex = /^\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)$/i;
var linkLineRegex = /\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)/gi;
var imageRegex = /\.(gif|jpe?g|tiff?|png|webp|bmp|tga|psd|ai)$/i;
function isUrl(text) {
  return urlRegex.test(text);
}
function isImage(text) {
  return imageRegex.test(text);
}
function isLinkedUrl(text) {
  return linkRegex.test(text);
}
function extractUrlFromLink(link) {
  const match = linkRegex.exec(link);
  if (!match || match.length < 3) return "";
  return match[2];
}

// src/editor-extensions.ts
var EditorExtensions = class {
  static getSelectedText(editor) {
    if (!editor.somethingSelected()) {
      const bounds = this.getWordBoundaries(editor);
      editor.setSelection(bounds.start, bounds.end);
    }
    return editor.getSelection();
  }
  static posFromIndex(content, index) {
    const substr = content.substring(0, index);
    let line = 0;
    let offset = -1;
    let r = -1;
    for (; (r = substr.indexOf("\n", r + 1)) !== -1; line++, offset = r) ;
    offset += 1;
    const ch = index - offset;
    return { line, ch };
  }
  static isCursorInRange(cursor, match) {
    var _a;
    const start = (_a = match.index) != null ? _a : 0;
    const end = start + match[0].length;
    return start <= cursor.ch && cursor.ch <= end;
  }
  static getWordBoundaries(editor) {
    var _a, _b;
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    for (const match of lineText.matchAll(linkLineRegex)) {
      if (this.isCursorInRange(cursor, match)) {
        const startCh = (_a = match.index) != null ? _a : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    for (const match of lineText.matchAll(lineUrlRegex)) {
      if (this.isCursorInRange(cursor, match)) {
        const startCh = (_b = match.index) != null ? _b : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    return { start: cursor, end: cursor };
  }
};

// src/card-generator.ts
var CardGenerator = class {
  constructor(editor, defaultView = "card") {
    this.editor = editor;
    this.defaultView = defaultView;
  }
  convert(url) {
    return __async(this, null, function* () {
      const selectedText = this.editor.getSelection();
      const placeholderId = this.randomId();
      const placeholder = `[Fetching Data#${placeholderId}](${url})`;
      this.editor.replaceSelection(placeholder);
      new import_obsidian2.Notice("Cards4Links: fetching metadata...");
      const metadata = yield this.fetchMetadata(url);
      const text = this.editor.getValue();
      const start = text.indexOf(placeholder);
      if (start < 0) {
        console.log(
          `Could not find placeholder "${placeholder}" in editor, bailing out; url ${url}`
        );
        return;
      }
      const end = start + placeholder.length;
      const startPos = EditorExtensions.posFromIndex(text, start);
      const endPos = EditorExtensions.posFromIndex(text, end);
      if (!metadata) {
        new import_obsidian2.Notice("Cards4Links: couldn't fetch link metadata");
        this.editor.replaceRange(selectedText || url, startPos, endPos);
        return;
      }
      this.editor.replaceRange(this.generateCodeBlock(metadata), startPos, endPos);
    });
  }
  generateCodeBlock(md) {
    const lines = ["\n```cardlink"];
    lines.push(`url: ${md.url}`);
    lines.push(`title: "${md.title}"`);
    if (md.description) lines.push(`description: "${md.description}"`);
    if (md.host) lines.push(`host: ${md.host}`);
    if (md.favicon) lines.push(`favicon: ${md.favicon}`);
    if (md.image) lines.push(`image: ${md.image}`);
    lines.push(`watched: false`);
    lines.push(`view: ${this.defaultView}`);
    lines.push("```\n");
    return lines.join("\n");
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      try {
        const res = yield (0, import_obsidian2.requestUrl)({ url });
        if (res.status !== 200) {
          console.log(`Cards4Links: bad response status ${res.status}`);
          return void 0;
        }
        const parser = new MetadataParser(url, res.text);
        return yield parser.parse();
      } catch (e) {
        console.log("Cards4Links fetch error:", e);
        return void 0;
      }
    });
  }
  randomId() {
    const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
    let result = "";
    for (let i = 0; i < 4; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }
};

// src/card-processor.ts
var import_obsidian3 = require("obsidian");
function createSvgIcon(viewBox, size, ...elements) {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", viewBox);
  svg.setAttribute("width", String(size));
  svg.setAttribute("height", String(size));
  for (const [tag, attrs] of elements) {
    const el = document.createElementNS("http://www.w3.org/2000/svg", tag);
    for (const [key, val] of Object.entries(attrs)) {
      el.setAttribute(key, val);
    }
    svg.appendChild(el);
  }
  return svg;
}
function detectContentType(host) {
  if (!host) return "article";
  const videoHosts = [
    "youtube.com",
    "youtu.be",
    "vimeo.com",
    "twitch.tv",
    "dailymotion.com",
    "kick.com",
    "facebook.com"
  ];
  return videoHosts.some((h) => host.includes(h)) ? "video" : "article";
}
var YamlParseError = class extends Error {
  constructor(msg) {
    super(msg);
    this.name = "YamlParseError";
  }
};
var NoRequiredParamsError = class extends Error {
  constructor(msg) {
    super(msg);
    this.name = "NoRequiredParamsError";
  }
};
var CardProcessor = class {
  constructor(app, thumbnailPosition = "right", defaultView = "card") {
    this.app = app;
    this.thumbnailPosition = thumbnailPosition;
    this.defaultView = defaultView;
    this.source = "";
    this.sections = [];
  }
  run(source, el) {
    this.source = source;
    const raw = source.split(/\n-{3,}\n/).map((s) => s.trim());
    this.sections = raw.length > 1 ? raw : [source];
    if (this.sections.length <= 1) {
      try {
        const data = this.parseYaml(source);
        el.appendChild(this.renderCard(data, source, 0));
      } catch (error) {
        el.appendChild(this.renderError(error));
      }
    } else {
      const group = el.createDiv({ cls: "cards4links-group" });
      for (let i = 0; i < this.sections.length; i++) {
        try {
          const data = this.parseYaml(this.sections[i]);
          group.appendChild(this.renderCard(data, this.sections[i], i));
        } catch (error) {
          group.appendChild(this.renderError(error));
        }
      }
    }
  }
  parseYaml(source) {
    var _a;
    let yaml;
    let indent = 0;
    const normalized = source.split(/\r?\n|\r|\n/g).map(
      (line) => line.replace(/^\t+/g, (tabs) => {
        if (indent === 0) indent = tabs.length;
        return " ".repeat(tabs.length);
      })
    ).join("\n");
    try {
      yaml = (0, import_obsidian3.parseYaml)(normalized);
    } catch (error) {
      console.log("Cards4Links YAML parse error:", error);
      throw new YamlParseError(
        "Failed to parse YAML. Check debug console for details."
      );
    }
    if (!yaml || !yaml.url || !yaml.title) {
      throw new NoRequiredParamsError(
        "Required params [url, title] not found."
      );
    }
    return {
      url: yaml.url,
      title: yaml.title,
      description: yaml.description,
      host: yaml.host,
      favicon: yaml.favicon,
      image: yaml.image,
      watched: yaml.watched === true,
      view: (_a = yaml.view) != null ? _a : "card",
      contentType: detectContentType(yaml.host)
    };
  }
  renderCard(data, source, cardIndex) {
    const view = data.view || "card";
    const needsUpgrade = !/^view:/m.test(source);
    const container = createDiv({
      cls: "cards4links-container",
      attr: {
        "data-thumbnail": this.thumbnailPosition,
        "data-view": view,
        "data-watched": data.watched ? "true" : "false"
      }
    });
    const card = container.createEl("a", {
      cls: "cards4links-card",
      attr: { href: data.url }
    });
    const main = card.createDiv({ cls: "cards4links-main" });
    const titleRow = main.createDiv({ cls: "cards4links-title-row" });
    titleRow.createSpan({
      cls: "cards4links-title-text",
      text: data.title
    });
    const actionsLeft = container.createDiv({ cls: "cards4links-actions-left" });
    if (needsUpgrade) {
      const upgradeBtn = actionsLeft.createEl("button", {
        cls: "cards4links-upgrade-btn clickable-icon",
        attr: { "aria-label": "Add view field to card" }
      });
      upgradeBtn.appendChild(
        createSvgIcon(
          "0 0 24 24",
          14,
          ["path", { d: "M5 10l7-7 7 7", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["path", { d: "M12 3v18", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
        )
      );
      upgradeBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        container.dataset.view = this.defaultView;
        const oldSource = this.source;
        const newSections = [...this.sections];
        newSections[cardIndex] = newSections[cardIndex] + `
view: ${this.defaultView}`;
        const newSource = newSections.join("\n---\n");
        this.replaceBlock(oldSource, newSource);
        this.sections = newSections;
        this.source = newSource;
        upgradeBtn.remove();
      });
    }
    const actions = container.createDiv({ cls: "cards4links-actions" });
    const viewCycle = ["card", "compact", "minimal"];
    const viewBtn = actions.createEl("button", {
      cls: "cards4links-view-btn clickable-icon",
      attr: { "aria-label": `View: ${view}` }
    });
    viewBtn.appendChild(
      createSvgIcon(
        "0 0 24 24",
        14,
        ["rect", { x: "3", y: "3", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
        ["rect", { x: "13", y: "3", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
        ["rect", { x: "3", y: "13", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
        ["rect", { x: "13", y: "13", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
      )
    );
    viewBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const currentView = container.dataset.view || "card";
      const next = viewCycle[(viewCycle.indexOf(currentView) + 1) % viewCycle.length];
      container.dataset.view = next;
      this.updateCardBlock(cardIndex, "view", next);
    });
    const label = data.contentType === "video" ? "Watched" : "Read";
    const watchToggleBtn = actions.createEl("button", {
      cls: "cards4links-watch-toggle clickable-icon",
      attr: {
        "aria-label": data.watched ? "Mark as Unread" : `Mark as ${label}`
      }
    });
    const checkedSvg = createSvgIcon(
      "0 0 24 24",
      14,
      ["circle", { cx: "12", cy: "12", r: "10", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
      ["path", { d: "M8 12l3 3 5-5", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
    );
    const uncheckedSvg = createSvgIcon(
      "0 0 24 24",
      14,
      ["circle", { cx: "12", cy: "12", r: "10", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
    );
    watchToggleBtn.appendChild(data.watched ? checkedSvg.cloneNode(true) : uncheckedSvg.cloneNode(true));
    watchToggleBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const currentlyWatched = container.dataset.watched === "true";
      const newWatched = !currentlyWatched;
      container.dataset.watched = newWatched ? "true" : "false";
      watchToggleBtn.empty();
      watchToggleBtn.appendChild(newWatched ? checkedSvg.cloneNode(true) : uncheckedSvg.cloneNode(true));
      watchToggleBtn.setAttr(
        "aria-label",
        newWatched ? "Mark as Unread" : `Mark as ${label}`
      );
      this.updateCardBlock(cardIndex, "watched", newWatched);
    });
    if (data.description) {
      main.createDiv({
        cls: "cards4links-description",
        text: data.description
      });
    }
    const hostRow = main.createDiv({ cls: "cards4links-host" });
    if (data.favicon) {
      hostRow.createEl("img", {
        cls: "cards4links-favicon",
        attr: { src: data.favicon }
      });
    }
    if (data.host) {
      hostRow.createSpan({ text: data.host });
    }
    if (data.image) {
      const img = card.createEl("img", {
        cls: "cards4links-thumbnail",
        attr: { src: data.image, draggable: "false" }
      });
      img.addEventListener("error", () => {
        img.classList.add("cards4links-thumbnail-hidden");
      });
    }
    const copyBtn = container.createEl("button", {
      cls: "cards4links-copy-url clickable-icon",
      attr: { "aria-label": `Copy URL
${data.url}` }
    });
    copyBtn.appendChild(
      createSvgIcon(
        "0 0 24 24",
        16,
        ["path", { fill: "currentColor", d: "M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z" }]
      )
    );
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void navigator.clipboard.writeText(data.url);
      new import_obsidian3.Notice("URL copied to clipboard");
    });
    return container;
  }
  updateCardBlock(cardIndex, field, value) {
    const section = this.sections[cardIndex];
    const fieldRegex = new RegExp(`^${field}:.*$`, "m");
    const newSection = fieldRegex.test(section) ? section.replace(fieldRegex, `${field}: ${value}`) : section + `
${field}: ${value}`;
    const newSections = [...this.sections];
    newSections[cardIndex] = newSection;
    const newSource = newSections.join("\n---\n");
    const oldSource = this.source;
    this.replaceBlock(oldSource, newSource);
    this.sections = newSections;
    this.source = newSource;
  }
  replaceBlock(oldSource, newSource) {
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!markdownView) {
      console.log("Cards4Links: no active MarkdownView");
      new import_obsidian3.Notice("Cards4Links: cannot edit in Reading view");
      return;
    }
    const editor = markdownView.editor;
    if (!editor) {
      console.log("Cards4Links: no editor available");
      return;
    }
    const text = editor.getValue();
    const blockRegex = /```cardlink\s*\n([\s\S]*?)```/g;
    let match;
    while ((match = blockRegex.exec(text)) !== null) {
      const blockContent = match[1];
      if (blockContent.replace(/\r\n/g, "\n").trimEnd() !== oldSource.replace(/\r\n/g, "\n").trimEnd()) continue;
      const lines = blockContent.split("\n");
      const hasPrefix = lines.some((l) => l.trim() && l.startsWith("> "));
      const finalContent = hasPrefix ? newSource.split("\n").map((l) => "> " + l).join("\n") : newSource;
      const startPos = EditorExtensions.posFromIndex(text, match.index);
      const endPos = EditorExtensions.posFromIndex(
        text,
        match.index + match[0].length
      );
      try {
        editor.replaceRange(
          `\`\`\`cardlink
${finalContent}
\`\`\``,
          startPos,
          endPos
        );
      } catch (e) {
        console.log("Cards4Links: failed to update code block", e);
        new import_obsidian3.Notice("Cards4Links: error updating card state");
      }
      break;
    }
  }
  renderError(error) {
    const container = createDiv({ cls: "cards4links-error" });
    container.setText(`cardlink error: ${error.message}`);
    return container;
  }
};

// src/main.ts
var Cards4Links = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.onPaste = (evt, editor) => __async(this, null, function* () {
      if (!this.settings.enhanceDefaultPaste) return;
      if (!navigator.onLine) return;
      if (!evt.clipboardData) return;
      if (evt.clipboardData.files.length > 0) return;
      const clipboardText = evt.clipboardData.getData("text/plain");
      if (!clipboardText) return;
      if (!isUrl(clipboardText) || isImage(clipboardText)) return;
      evt.stopPropagation();
      evt.preventDefault();
      const generator = new CardGenerator(editor, this.settings.defaultView);
      yield generator.convert(clipboardText);
    });
    this.onEditorMenu = (menu) => {
      if (!this.settings.showInMenuItem) return;
      menu.addItem((item) => {
        item.setTitle("Paste URL and enhance to card link").setIcon("paste").onClick(() => __async(this, null, function* () {
          const editor = this.getEditor();
          if (!editor) return;
          yield this.manualPasteAndEnhance(editor);
        }));
      });
      if (!navigator.onLine) return;
      menu.addItem((item) => {
        item.setTitle("Enhance selected URL to card link").setIcon("link").onClick(() => {
          const editor = this.getEditor();
          if (!editor) return;
          void this.enhanceSelected(editor);
        });
      });
    };
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.registerMarkdownCodeBlockProcessor("cardlink", (source, el) => {
        const processor = new CardProcessor(
          this.app,
          this.settings.thumbnailPosition,
          this.settings.defaultView
        );
        processor.run(source, el);
      });
      this.addCommand({
        id: "paste-and-enhance",
        name: "Paste URL and enhance to card link",
        editorCallback: (editor) => __async(this, null, function* () {
          yield this.manualPasteAndEnhance(editor);
        }),
        hotkeys: []
      });
      this.addCommand({
        id: "upgrade-old-cards",
        name: "Add view field to old cardlink cards",
        editorCallback: (editor) => {
          this.upgradeOldCards(editor);
        }
      });
      this.addCommand({
        id: "enhance-selected-url",
        name: "Enhance selected URL to card link",
        editorCheckCallback: (checking, editor) => {
          if (!navigator.onLine) return false;
          if (checking) return true;
          void this.enhanceSelected(editor);
          return;
        },
        hotkeys: [{ modifiers: ["Mod", "Shift"], key: "e" }]
      });
      this.registerEvent(
        this.app.workspace.on("editor-paste", this.onPaste)
      );
      this.registerEvent(
        this.app.workspace.on("editor-menu", this.onEditorMenu)
      );
      this.addSettingTab(new Cards4LinksSettingTab(this.app, this));
    });
  }
  enhanceSelected(editor) {
    return __async(this, null, function* () {
      const selected = (EditorExtensions.getSelectedText(editor) || "").trim();
      const generator = new CardGenerator(editor, this.settings.defaultView);
      for (const line of selected.split(/[\n ]/)) {
        if (isUrl(line)) {
          yield generator.convert(line);
        } else if (isLinkedUrl(line)) {
          const url = extractUrlFromLink(line);
          if (url) yield generator.convert(url);
        }
      }
    });
  }
  manualPasteAndEnhance(editor) {
    return __async(this, null, function* () {
      const clipboardText = yield navigator.clipboard.readText();
      if (!clipboardText) return;
      if (!navigator.onLine) {
        editor.replaceSelection(clipboardText);
        return;
      }
      if (!isUrl(clipboardText) || isImage(clipboardText)) {
        editor.replaceSelection(clipboardText);
        return;
      }
      const generator = new CardGenerator(editor, this.settings.defaultView);
      yield generator.convert(clipboardText);
    });
  }
  upgradeOldCards(editor) {
    const text = editor.getValue();
    const blockRegex = /```cardlink\n([\s\S]*?)```/g;
    const replacements = [];
    let match;
    while ((match = blockRegex.exec(text)) !== null) {
      const blockContent = match[1].replace(/\r/g, "");
      if (/^view:/m.test(blockContent)) continue;
      const newContent = blockContent + (blockContent.endsWith("\n") ? "" : "\n") + `view: ${this.settings.defaultView}`;
      const startPos = EditorExtensions.posFromIndex(text, match.index);
      const endPos = EditorExtensions.posFromIndex(
        text,
        match.index + match[0].length
      );
      replacements.push({
        start: startPos,
        end: endPos,
        content: `\`\`\`cardlink
${newContent}\`\`\``
      });
    }
    if (replacements.length === 0) {
      new import_obsidian4.Notice("Cards4Links: no old cards found");
      return;
    }
    replacements.reverse();
    for (const r of replacements) {
      editor.replaceRange(r.content, r.start, r.end);
    }
    new import_obsidian4.Notice(`Cards4Links: updated ${replacements.length} card(s)`);
  }
  getEditor() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    return view == null ? void 0 : view.editor;
  }
  loadSettings() {
    return __async(this, null, function* () {
      const data = yield this.loadData();
      this.settings = Object.assign(
        {},
        DEFAULT_SETTINGS,
        data
      );
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
