/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Cards4Links
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian4 = require("obsidian");

// src/cache-cleanup-modal.ts
var import_obsidian3 = require("obsidian");

// src/i18n.ts
var import_obsidian = require("obsidian");
var en = {
  "command.pasteAndEnhance": "Paste URL and enhance to card link",
  "command.upgradeOldCards": "Add view field to old cardlink cards",
  "command.enhanceSelected": "Enhance selected URL to card link",
  "command.createCarousel": "Create carousel from selected URLs",
  "command.openSettings": "Open plugin settings",
  "notice.welcome": "Cards4Links activated! Paste a URL into a note, or select a URL and press Mod+Shift+E.",
  "milestone.1": "First card created! \u{1F389} Enable 'Enhance default paste' in settings to convert URLs automatically on paste.",
  "milestone.3": "3 cards created! Select 2+ URLs and press Mod+Shift+C to build a carousel.",
  "milestone.5": "5 cards created! \u{1F389} Thanks for using Cards4Links! https://github.com/Mats324/cards4links",
  "milestone.10": "10 cards created! Try a card theme (light/dark) in settings for a different look.",
  "milestone.25": "25 cards created! Enable the 'watched/read' checkbox to track videos and articles.",
  "milestone.50": "50 cards created! Explore other card views (compact, minimal) to save space.",
  "milestone.100": "100 cards created! Turn on 'Cache images locally' to keep card images available offline.",
  "notice.selectTwoUrls": "Cards4Links: select 2+ URLs to create a carousel",
  "notice.noOldCards": "Cards4Links: no old cards found",
  "notice.updatedCards": "Cards4Links: updated {count} card(s)",
  "notice.fetchingMetadata": "Cards4Links: fetching metadata...",
  "notice.fetchFailed": "Cards4Links: couldn't fetch link metadata",
  "notice.fetchingMetadataGroup": "Cards4Links: fetching metadata for {count} links...",
  "notice.fetchFailedAll": "Cards4Links: couldn't fetch any link metadata",
  "notice.createdCarousel": "Cards4Links: created carousel with {count} cards",
  "notice.urlCopied": "URL copied to clipboard",
  "notice.cannotEditReading": "Cards4Links: cannot edit in Reading view",
  "notice.errorUpdatingCard": "Cards4Links: error updating card state",
  "notice.imageLoadFailed": "Failed to load image. Please try a different URL.",
  "error.yamlParse": "Failed to parse YAML. Check debug console for details.",
  "error.requiredParams": "Required params [url, title] not found.",
  "error.cardlink": "cardlink error: {message}",
  "label.watched": "Watched",
  "label.read": "Read",
  "aria.carousel": "Card carousel",
  "aria.carouselRoledescription": "carousel",
  "aria.slideRoledescription": "slide",
  "aria.slideOf": "Slide {current} of {total}",
  "aria.slideNavigation": "Slide navigation",
  "aria.goToSlide": "Go to slide {index}",
  "aria.previousSlide": "Previous slide",
  "aria.nextSlide": "Next slide",
  "aria.addViewField": "Add view field to card",
  "aria.view": "View: {view}",
  "aria.markAs": "Mark as {label}",
  "aria.markUnread": "Mark as Unread",
  "aria.copyUrl": "Copy URL\n{url}",
  "placeholder.setImage": "Set image",
  "placeholder.addDescription": "Add description",
  "modal.setImageTitle": "Set card image",
  "modal.imageUrl": "Image URL",
  "modal.imageUrlDesc": "Enter or paste a URL for the card image",
  "modal.pasteFromClipboard": "Paste from clipboard",
  "modal.setDescriptionTitle": "Set card description",
  "modal.description": "Description",
  "ui.save": "Save",
  "ui.cancel": "Cancel",
  "settings.language": "Language",
  "settings.languageDesc": "Interface language (auto follows the Obsidian language)",
  "settings.language.auto": "Auto",
  "settings.language.en": "English",
  "settings.language.it": "Italiano",
  "settings.cardsCreated": "Cards created",
  "settings.cardsCreatedDesc": "Number of cards generated with Cards4Links since the last reset: {count}",
  "settings.resetCounter": "Reset counter",
  "settings.resetCounterConfirm": "Reset the card counter? This will also restart the milestone notifications.",
  "settings.enhancePaste": "Enhance default paste",
  "settings.enhancePasteDesc": "Automatically fetch metadata when pasting a URL with the default paste command",
  "settings.thumbnailPosition": "Thumbnail position",
  "settings.thumbnailPositionDesc": "Where to show the thumbnail image in the card",
  "settings.thumbnail.right": "Right",
  "settings.thumbnail.left": "Left",
  "settings.thumbnail.none": "No thumbnail",
  "settings.showInMenu": "Show commands in menu item",
  "settings.showInMenuDesc": "Add paste/enhance commands to the right-click context menu",
  "settings.enableWatched": "Enable watched/read checkbox",
  "settings.enableWatchedDesc": "Show a checkbox on cards to track watched (video) or read (article) status",
  "settings.defaultView": "Default card view",
  "settings.defaultViewDesc": "Default view style for newly created cards",
  "settings.view.card": "Card",
  "settings.view.compact": "Compact",
  "settings.view.minimal": "Minimal",
  "settings.view.carousel": "Carousel",
  "settings.theme": "Card theme",
  "settings.themeDesc": "Override card colors (default follows Obsidian theme)",
  "settings.theme.default": "Default",
  "settings.theme.light": "Light",
  "settings.theme.dark": "Dark",
  "settings.cacheImages": "Cache images locally",
  "settings.cacheImagesDesc": "Download card images to the vault for offline access",
  "settings.cacheStorage": "Cache storage",
  "settings.cacheStorageDesc": "Store images in a global vault folder or next to each note",
  "settings.cacheLocation.vault": "Global folder",
  "settings.cacheLocation.note": "Per note",
  "settings.cacheFolder": "Cache folder name",
  "settings.cacheFolderDesc": "Folder path for cached images (vault root)",
  "settings.cacheTtl": "Cache TTL",
  "settings.cacheTtlDesc": "How long before re-downloading a cached image",
  "settings.ttl.7": "7 days",
  "settings.ttl.30": "30 days",
  "settings.ttl.90": "90 days",
  "settings.ttl.180": "180 days",
  "settings.ttl.0": "Never expire",
  "settings.manageCache": "Manage cache",
  "settings.manageCacheDesc": "View cache contents and clean up files",
  "settings.manageCacheButton": "Manage cache\u2026",
  "cache.title": "Cache Cleanup",
  "cache.scanning": "Scanning cache\u2026",
  "cache.summary": "{count} files \u2014 {size}",
  "cache.summaryExpired": " \u2014 {count} expired",
  "cache.selectAll": "Select all",
  "cache.selectExpired": "Select expired",
  "cache.selectOrphans": "Select orphans",
  "cache.deselectAll": "Deselect all",
  "cache.headerFile": "File",
  "cache.headerSize": "Size",
  "cache.headerAge": "Age",
  "cache.orphan": "orphan",
  "cache.expired": "expired",
  "cache.ok": "ok",
  "cache.deleteSelected": "Delete selected",
  "notice.noFilesSelected": "No files selected",
  "notice.deletedFiles": "Deleted {count} file(s)",
  "cache.age.today": "today",
  "cache.age.oneDay": "1 day",
  "cache.age.days": "{days} days",
  "cache.age.oneMonth": "1 month",
  "cache.age.months": "{months} months"
};
var it = {
  "command.pasteAndEnhance": "Incolla URL e converti in card link",
  "command.upgradeOldCards": "Aggiungi campo view alle card cardlink datate",
  "command.enhanceSelected": "Converti l'URL selezionato in card link",
  "command.createCarousel": "Crea carosello dagli URL selezionati",
  "command.openSettings": "Apri le impostazioni del plugin",
  "notice.welcome": "Cards4Links attivato! Incolla un URL in una nota, oppure seleziona un URL e premi Mod+Shift+E.",
  "milestone.1": "Prima card creata! \u{1F389} Attiva 'Migliora incolla predefinito' nelle impostazioni per convertire automaticamente gli URL in card all'incolla.",
  "milestone.3": "3 card create! Seleziona 2+ URL e premi Mod+Shift+C per creare un carosello.",
  "milestone.5": "5 card create! \u{1F389} Grazie per usare Cards4Links! https://github.com/Mats324/cards4links",
  "milestone.10": "10 card create! Prova un tema card (chiaro/scuro) nelle impostazioni per un aspetto diverso.",
  "milestone.25": "25 card create! Attiva la checkbox 'guardato/letto' per monitorare video e articoli.",
  "milestone.50": "50 card create! Esplora le altre viste card (compatta, minimale) per risparmiare spazio.",
  "milestone.100": "100 card create! Attiva 'Salva immagini localmente' per mantenere le immagini delle card disponibili offline.",
  "notice.selectTwoUrls": "Cards4Links: seleziona 2+ URL per creare un carosello",
  "notice.noOldCards": "Cards4Links: nessuna card datata trovata",
  "notice.updatedCards": "Cards4Links: aggiornate {count} card",
  "notice.fetchingMetadata": "Cards4Links: recupero metadati...",
  "notice.fetchFailed": "Cards4Links: impossibile recuperare i metadati del link",
  "notice.fetchingMetadataGroup": "Cards4Links: recupero metadati per {count} link...",
  "notice.fetchFailedAll": "Cards4Links: impossibile recuperare i metadati di alcun link",
  "notice.createdCarousel": "Cards4Links: carosello creato con {count} card",
  "notice.urlCopied": "URL copiato negli appunti",
  "notice.cannotEditReading": "Cards4Links: impossibile modificare in Visualizzazione Lettura",
  "notice.errorUpdatingCard": "Cards4Links: errore durante l'aggiornamento della card",
  "notice.imageLoadFailed": "Impossibile caricare l'immagine. Prova con un URL diverso.",
  "error.yamlParse": "Impossibile analizzare lo YAML. Controlla la console di debug per i dettagli.",
  "error.requiredParams": "Parametri obbligatori [url, title] non trovati.",
  "error.cardlink": "errore cardlink: {message}",
  "label.watched": "Visto",
  "label.read": "Letto",
  "aria.carousel": "Carosello di card",
  "aria.carouselRoledescription": "carosello",
  "aria.slideRoledescription": "slide",
  "aria.slideOf": "Slide {current} di {total}",
  "aria.slideNavigation": "Navigazione slide",
  "aria.goToSlide": "Vai alla slide {index}",
  "aria.previousSlide": "Slide precedente",
  "aria.nextSlide": "Slide successiva",
  "aria.addViewField": "Aggiungi campo view alla card",
  "aria.view": "Vista: {view}",
  "aria.markAs": "Segna come {label}",
  "aria.markUnread": "Segna come Non Letto",
  "aria.copyUrl": "Copia URL\n{url}",
  "placeholder.setImage": "Imposta immagine",
  "placeholder.addDescription": "Aggiungi descrizione",
  "modal.setImageTitle": "Imposta immagine della card",
  "modal.imageUrl": "URL immagine",
  "modal.imageUrlDesc": "Inserisci o incolla l'URL per l'immagine della card",
  "modal.pasteFromClipboard": "Incolla dagli appunti",
  "modal.setDescriptionTitle": "Imposta descrizione della card",
  "modal.description": "Descrizione",
  "ui.save": "Salva",
  "ui.cancel": "Annulla",
  "settings.language": "Lingua",
  "settings.languageDesc": "Lingua dell'interfaccia (auto segue la lingua di Obsidian)",
  "settings.language.auto": "Auto",
  "settings.language.en": "English",
  "settings.language.it": "Italiano",
  "settings.cardsCreated": "Card create",
  "settings.cardsCreatedDesc": "Numero di card generate con Cards4Links dall'ultimo reset: {count}",
  "settings.resetCounter": "Azzera contatore",
  "settings.resetCounterConfirm": "Azzera il contatore delle card? Verranno riattivate anche le notifiche dei traguardi.",
  "settings.enhancePaste": "Migliora incolla predefinito",
  "settings.enhancePasteDesc": "Recupera automaticamente i metadati quando incolli un URL con il comando di incolla predefinito",
  "settings.thumbnailPosition": "Posizione anteprima",
  "settings.thumbnailPositionDesc": "Dove mostrare l'immagine di anteprima nella card",
  "settings.thumbnail.right": "Destra",
  "settings.thumbnail.left": "Sinistra",
  "settings.thumbnail.none": "Nessuna anteprima",
  "settings.showInMenu": "Mostra comandi nel menu contestuale",
  "settings.showInMenuDesc": "Aggiungi i comandi incolla/converti al menu contestuale del tasto destro",
  "settings.enableWatched": "Attiva checkbox visto/letto",
  "settings.enableWatchedDesc": "Mostra una checkbox sulle card per monitorare lo stato visto (video) o letto (articolo)",
  "settings.defaultView": "Vista predefinita della card",
  "settings.defaultViewDesc": "Stile di vista predefinito per le nuove card",
  "settings.view.card": "Card",
  "settings.view.compact": "Compatta",
  "settings.view.minimal": "Minimale",
  "settings.view.carousel": "Carosello",
  "settings.theme": "Tema card",
  "settings.themeDesc": "Sovrascrivi i colori delle card (predefinito segue il tema di Obsidian)",
  "settings.theme.default": "Predefinito",
  "settings.theme.light": "Chiaro",
  "settings.theme.dark": "Scuro",
  "settings.cacheImages": "Salva immagini localmente",
  "settings.cacheImagesDesc": "Scarica le immagini delle card nel vault per l'accesso offline",
  "settings.cacheStorage": "Archiviazione cache",
  "settings.cacheStorageDesc": "Salva le immagini in una cartella globale del vault o accanto a ogni nota",
  "settings.cacheLocation.vault": "Cartella globale",
  "settings.cacheLocation.note": "Per nota",
  "settings.cacheFolder": "Nome cartella cache",
  "settings.cacheFolderDesc": "Percorso cartella per le immagini in cache (root del vault)",
  "settings.cacheTtl": "TTL cache",
  "settings.cacheTtlDesc": "Dopo quanto tempo riscaricare un'immagine in cache",
  "settings.ttl.7": "7 giorni",
  "settings.ttl.30": "30 giorni",
  "settings.ttl.90": "90 giorni",
  "settings.ttl.180": "180 giorni",
  "settings.ttl.0": "Mai",
  "settings.manageCache": "Gestisci cache",
  "settings.manageCacheDesc": "Visualizza il contenuto della cache e ripulisci i file",
  "settings.manageCacheButton": "Gestisci cache\u2026",
  "cache.title": "Pulizia cache",
  "cache.scanning": "Analisi cache in corso\u2026",
  "cache.summary": "{count} file \u2014 {size}",
  "cache.summaryExpired": " \u2014 {count} scaduti",
  "cache.selectAll": "Seleziona tutto",
  "cache.selectExpired": "Seleziona scaduti",
  "cache.selectOrphans": "Seleziona orfani",
  "cache.deselectAll": "Deseleziona tutto",
  "cache.headerFile": "File",
  "cache.headerSize": "Dimensione",
  "cache.headerAge": "Et\xE0",
  "cache.orphan": "orfano",
  "cache.expired": "scaduto",
  "cache.ok": "ok",
  "cache.deleteSelected": "Elimina selezionati",
  "notice.noFilesSelected": "Nessun file selezionato",
  "notice.deletedFiles": "Eliminati {count} file",
  "cache.age.today": "oggi",
  "cache.age.oneDay": "1 giorno",
  "cache.age.days": "{days} giorni",
  "cache.age.oneMonth": "1 mese",
  "cache.age.months": "{months} mesi"
};
var dictionaries = { en, it };
var currentLang = "en";
function setLanguage(lang) {
  currentLang = lang;
}
function detectLang() {
  var _a, _b;
  let locale = "";
  try {
    locale = import_obsidian.moment.locale();
  } catch (e) {
    locale = (_a = navigator == null ? void 0 : navigator.language) != null ? _a : "";
  }
  if (!locale) locale = (_b = navigator == null ? void 0 : navigator.language) != null ? _b : "";
  return locale.toLowerCase().startsWith("it") ? "it" : "en";
}
function resolveLang(setting) {
  if (setting === "en" || setting === "it") return setting;
  return detectLang();
}
function t(key, vars) {
  let str = dictionaries[currentLang][key];
  if (vars) {
    for (const [name, value] of Object.entries(vars)) {
      str = str.split(`{${name}}`).join(String(value));
    }
  }
  return str;
}

// src/image-cache.ts
var import_obsidian2 = require("obsidian");
function extension(url) {
  const match = url.match(/\.(jpe?g|png|gif|webp|bmp|svg|ico)(\?|#|$)/i);
  return match ? match[1].toLowerCase() : "jpg";
}
function hashUrl(url) {
  return __async(this, null, function* () {
    const data = new TextEncoder().encode(url);
    const hash = yield crypto.subtle.digest("SHA-256", data);
    const hex = Array.from(new Uint8Array(hash.slice(0, 8))).map((b) => b.toString(16).padStart(2, "0")).join("");
    return `${hex}.${extension(url)}`;
  });
}
function downloadImage(url) {
  return __async(this, null, function* () {
    const res = yield (0, import_obsidian2.requestUrl)(url);
    return res.arrayBuffer;
  });
}
function getCacheFolderPath(activeFile, location, folderName) {
  if (location === "note-relative" && activeFile) {
    const parent = activeFile.parent;
    return parent ? `${parent.path}/${folderName}` : folderName;
  }
  return folderName;
}
function ensureFolder(app, path) {
  return __async(this, null, function* () {
    const existing = app.vault.getAbstractFileByPath(path);
    if (existing && existing instanceof import_obsidian2.TFolder) return;
    yield app.vault.createFolder(path);
  });
}
var MANIFEST_FILE = "_manifest.json";
function getManifest(app, folder) {
  return __async(this, null, function* () {
    const file = app.vault.getAbstractFileByPath(`${folder}/${MANIFEST_FILE}`);
    if (!file || !(file instanceof import_obsidian2.TFile)) {
      return { version: 1, files: [] };
    }
    try {
      const content = yield app.vault.read(file);
      return JSON.parse(content);
    } catch (e) {
      return { version: 1, files: [] };
    }
  });
}
function saveManifest(app, folder, manifest) {
  return __async(this, null, function* () {
    const path = `${folder}/${MANIFEST_FILE}`;
    const existing = app.vault.getAbstractFileByPath(path);
    const content = JSON.stringify(manifest, null, 2);
    if (existing && existing instanceof import_obsidian2.TFile) {
      yield app.vault.modify(existing, content);
    } else {
      yield app.vault.create(path, content);
    }
  });
}
function addToManifest(app, folder, entry) {
  return __async(this, null, function* () {
    const manifest = yield getManifest(app, folder);
    const idx = manifest.files.findIndex((f) => f.filename === entry.filename);
    if (idx >= 0) {
      manifest.files[idx] = entry;
    } else {
      manifest.files.push(entry);
    }
    yield saveManifest(app, folder, manifest);
  });
}
function removeFromManifest(app, folder, filenames) {
  return __async(this, null, function* () {
    const manifest = yield getManifest(app, folder);
    manifest.files = manifest.files.filter(
      (f) => !filenames.includes(f.filename)
    );
    yield saveManifest(app, folder, manifest);
  });
}
function deleteFiles(app, folder, filenames) {
  return __async(this, null, function* () {
    for (const name of filenames) {
      if (name === MANIFEST_FILE) continue;
      const path = `${folder}/${name}`;
      const file = app.vault.getAbstractFileByPath(path);
      if (file) {
        yield app.vault.delete(file);
      }
    }
    yield removeFromManifest(app, folder, filenames);
  });
}
function resolveResourceUrl(app, localPath) {
  return __async(this, null, function* () {
    const file = app.vault.getAbstractFileByPath(localPath);
    if (!file || !(file instanceof import_obsidian2.TFile)) return null;
    return app.vault.getResourcePath(file);
  });
}
function scanReferences(app) {
  return __async(this, null, function* () {
    const refs = /* @__PURE__ */ new Set();
    const files = app.vault.getMarkdownFiles();
    for (const file of files) {
      const content = yield app.vault.cachedRead(file);
      const regex = /imageLocal:\s*(\S+)/g;
      let match;
      while ((match = regex.exec(content)) !== null) {
        refs.add(match[1]);
      }
    }
    return refs;
  });
}
function isExpired(entry, ttlDays) {
  if (ttlDays <= 0) return false;
  const age = Date.now() - new Date(entry.cachedAt).getTime();
  return age > ttlDays * 864e5;
}

// src/cache-cleanup-modal.ts
function fmtSize(bytes) {
  if (bytes >= 1048576) return `${(bytes / 1048576).toFixed(1)} MB`;
  if (bytes >= 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${bytes} B`;
}
function fmtAge(iso) {
  const days = Math.floor(
    (Date.now() - new Date(iso).getTime()) / 864e5
  );
  if (days < 1) return t("cache.age.today");
  if (days === 1) return t("cache.age.oneDay");
  if (days < 30) return t("cache.age.days", { days });
  const months = Math.floor(days / 30);
  return months === 1 ? t("cache.age.oneMonth") : t("cache.age.months", { months });
}
var CacheCleanupModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.rows = [];
    this.folder = "";
    this.loading = true;
  }
  onOpen() {
    return __async(this, null, function* () {
      const { contentEl } = this;
      contentEl.addClass("cards4links-modal");
      contentEl.empty();
      contentEl.createEl("h2", { text: t("cache.title") });
      this.container = contentEl.createDiv();
      this.container.setText(t("cache.scanning"));
      yield this.loadData();
      this.render();
    });
  }
  loadData() {
    return __async(this, null, function* () {
      this.folder = getCacheFolderPath(
        this.app.workspace.getActiveFile(),
        this.plugin.settings.cacheLocation,
        this.plugin.settings.cacheFolder
      );
      const manifest = yield getManifest(this.app, this.folder);
      const refs = yield scanReferences(this.app);
      const ttl = this.plugin.settings.cacheTTL;
      this.rows = manifest.files.map((entry) => ({
        entry,
        checked: false,
        referenced: refs.has(entry.filename) || refs.has(`${this.folder}/${entry.filename}`),
        expired: isExpired(entry, ttl)
      }));
      this.loading = false;
    });
  }
  render() {
    this.container.empty();
    if (this.loading) {
      this.container.setText(t("cache.scanning"));
      return;
    }
    const totalSize = this.rows.reduce((s, r) => s + r.entry.size, 0);
    const expiredCount = this.rows.filter((r) => r.expired).length;
    const orphanCount = this.rows.filter((r) => !r.referenced).length;
    const summaryEl = this.container.createDiv({ cls: "cards4links-cache-summary" });
    summaryEl.createSpan({
      text: t("cache.summary", {
        count: this.rows.length,
        size: fmtSize(totalSize)
      })
    });
    if (expiredCount > 0) {
      summaryEl.createSpan({
        text: t("cache.summaryExpired", { count: expiredCount })
      });
    }
    const actionsEl = this.container.createDiv({ cls: "cards4links-cache-actions" });
    actionsEl.createEl("button", { text: t("cache.selectAll"), cls: "clickable-icon" }).addEventListener("click", () => {
      this.rows.forEach((r) => r.checked = true);
      this.render();
    });
    if (expiredCount > 0) {
      actionsEl.createEl("button", { text: t("cache.selectExpired"), cls: "clickable-icon" }).addEventListener("click", () => {
        this.rows.forEach((r) => r.checked = r.expired);
        this.render();
      });
    }
    if (orphanCount > 0) {
      actionsEl.createEl("button", { text: t("cache.selectOrphans"), cls: "clickable-icon" }).addEventListener("click", () => {
        this.rows.forEach((r) => r.checked = !r.referenced);
        this.render();
      });
    }
    actionsEl.createEl("button", { text: t("cache.deselectAll"), cls: "clickable-icon" }).addEventListener("click", () => {
      this.rows.forEach((r) => r.checked = false);
      this.render();
    });
    const table = this.container.createEl("table", { cls: "cards4links-cache-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "" });
    headerRow.createEl("th", { text: t("cache.headerFile") });
    headerRow.createEl("th", { text: t("cache.headerSize") });
    headerRow.createEl("th", { text: t("cache.headerAge") });
    headerRow.createEl("th", { text: "" });
    const tbody = table.createEl("tbody");
    for (const row of this.rows) {
      const tr = tbody.createEl("tr");
      tr.addClass("cards4links-cache-row");
      const cbTd = tr.createEl("td");
      const cb = cbTd.createEl("input", { attr: { type: "checkbox" } });
      cb.checked = row.checked;
      cb.addEventListener("change", () => {
        row.checked = cb.checked;
      });
      tr.createEl("td", { text: row.entry.filename });
      tr.createEl("td", { text: fmtSize(row.entry.size) });
      tr.createEl("td", { text: fmtAge(row.entry.cachedAt) });
      const statusTd = tr.createEl("td");
      if (!row.referenced) {
        statusTd.createSpan({ text: t("cache.orphan"), cls: "cards4links-cache-orphan" });
      } else if (row.expired) {
        statusTd.createSpan({ text: t("cache.expired"), cls: "cards4links-cache-expired" });
      } else {
        statusTd.createSpan({ text: t("cache.ok"), cls: "cards4links-cache-ok" });
      }
    }
    const deleteBtn = this.container.createEl("button", {
      cls: "mod-cta",
      text: t("cache.deleteSelected")
    });
    deleteBtn.addEventListener("click", () => __async(this, null, function* () {
      const selected = this.rows.filter((r) => r.checked);
      if (selected.length === 0) {
        new import_obsidian3.Notice(t("notice.noFilesSelected"));
        return;
      }
      const filenames = selected.map((r) => r.entry.filename);
      yield deleteFiles(this.app, this.folder, filenames);
      this.rows = this.rows.filter((r) => !r.checked);
      new import_obsidian3.Notice(t("notice.deletedFiles", { count: filenames.length }));
      this.render();
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
function isThumbnailPosition(v) {
  return v === "right" || v === "left" || v === "none";
}
function isCardView(v) {
  return v === "card" || v === "compact" || v === "minimal" || v === "carousel";
}
function isCardTheme(v) {
  return v === "default" || v === "light" || v === "dark";
}
var DEFAULT_SETTINGS = {
  language: "auto",
  enhanceDefaultPaste: false,
  thumbnailPosition: "right",
  showInMenuItem: true,
  enableWatched: false,
  defaultView: "card",
  theme: "default",
  cacheImages: false,
  cacheFolder: "cards4links-cache",
  cacheLocation: "vault-absolute",
  cacheTTL: 30,
  cardsCreated: 0,
  welcomeShown: false,
  milestonesShown: []
};
var Cards4LinksSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName(t("settings.language")).setDesc(t("settings.languageDesc")).addDropdown(
      (dropdown) => dropdown.addOption("auto", t("settings.language.auto")).addOption("en", t("settings.language.en")).addOption("it", t("settings.language.it")).setValue(this.plugin.settings.language).onChange((value) => __async(this, null, function* () {
        if (value !== "auto" && value !== "en" && value !== "it") return;
        this.plugin.setLanguage(value);
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
    const counterSetting = new import_obsidian4.Setting(containerEl).setName(t("settings.cardsCreated")).setDesc(
      t("settings.cardsCreatedDesc", {
        count: this.plugin.settings.cardsCreated
      })
    );
    counterSetting.addButton(
      (btn) => btn.setButtonText(t("settings.resetCounter")).setWarning().onClick(() => __async(this, null, function* () {
        const confirmed = window.confirm(t("settings.resetCounterConfirm"));
        if (!confirmed) return;
        this.plugin.settings.cardsCreated = 0;
        this.plugin.settings.milestonesShown = [];
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
    new import_obsidian4.Setting(containerEl).setName(t("settings.enhancePaste")).setDesc(t("settings.enhancePasteDesc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enhanceDefaultPaste).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.enhanceDefaultPaste = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian4.Setting(containerEl).setName(t("settings.thumbnailPosition")).setDesc(t("settings.thumbnailPositionDesc")).addDropdown(
      (dropdown) => dropdown.addOption("right", t("settings.thumbnail.right")).addOption("left", t("settings.thumbnail.left")).addOption("none", t("settings.thumbnail.none")).setValue(this.plugin.settings.thumbnailPosition).onChange((value) => __async(this, null, function* () {
        if (!isThumbnailPosition(value)) return;
        this.plugin.settings.thumbnailPosition = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian4.Setting(containerEl).setName(t("settings.showInMenu")).setDesc(t("settings.showInMenuDesc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showInMenuItem).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showInMenuItem = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian4.Setting(containerEl).setName(t("settings.enableWatched")).setDesc(t("settings.enableWatchedDesc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableWatched).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.enableWatched = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian4.Setting(containerEl).setName(t("settings.defaultView")).setDesc(t("settings.defaultViewDesc")).addDropdown(
      (dropdown) => dropdown.addOption("card", t("settings.view.card")).addOption("compact", t("settings.view.compact")).addOption("minimal", t("settings.view.minimal")).setValue(this.plugin.settings.defaultView).onChange((value) => __async(this, null, function* () {
        if (!isCardView(value)) return;
        this.plugin.settings.defaultView = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian4.Setting(containerEl).setName(t("settings.theme")).setDesc(t("settings.themeDesc")).addDropdown(
      (dropdown) => dropdown.addOption("default", t("settings.theme.default")).addOption("light", t("settings.theme.light")).addOption("dark", t("settings.theme.dark")).setValue(this.plugin.settings.theme).onChange((value) => __async(this, null, function* () {
        if (!isCardTheme(value)) return;
        this.plugin.settings.theme = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian4.Setting(containerEl).setName(t("settings.cacheImages")).setDesc(t("settings.cacheImagesDesc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.cacheImages).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.cacheImages = value;
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
    if (this.plugin.settings.cacheImages) {
      new import_obsidian4.Setting(containerEl).setName(t("settings.cacheStorage")).setDesc(t("settings.cacheStorageDesc")).addDropdown(
        (dropdown) => dropdown.addOption("vault-absolute", t("settings.cacheLocation.vault")).addOption("note-relative", t("settings.cacheLocation.note")).setValue(this.plugin.settings.cacheLocation).onChange((value) => __async(this, null, function* () {
          if (value !== "vault-absolute" && value !== "note-relative")
            return;
          this.plugin.settings.cacheLocation = value;
          yield this.plugin.saveSettings();
          this.display();
        }))
      );
      if (this.plugin.settings.cacheLocation === "vault-absolute") {
        new import_obsidian4.Setting(containerEl).setName(t("settings.cacheFolder")).setDesc(t("settings.cacheFolderDesc")).addText(
          (text) => text.setValue(this.plugin.settings.cacheFolder).onChange((value) => __async(this, null, function* () {
            this.plugin.settings.cacheFolder = value || "cards4links-cache";
            yield this.plugin.saveSettings();
          }))
        );
      }
      new import_obsidian4.Setting(containerEl).setName(t("settings.cacheTtl")).setDesc(t("settings.cacheTtlDesc")).addDropdown(
        (dropdown) => dropdown.addOption("7", t("settings.ttl.7")).addOption("30", t("settings.ttl.30")).addOption("90", t("settings.ttl.90")).addOption("180", t("settings.ttl.180")).addOption("0", t("settings.ttl.0")).setValue(String(this.plugin.settings.cacheTTL)).onChange((value) => __async(this, null, function* () {
          this.plugin.settings.cacheTTL = parseInt(value);
          yield this.plugin.saveSettings();
        }))
      );
      new import_obsidian4.Setting(containerEl).setName(t("settings.manageCache")).setDesc(t("settings.manageCacheDesc")).addButton(
        (btn) => btn.setButtonText(t("settings.manageCacheButton")).onClick(() => {
          const modal = new CacheCleanupModal(
            this.plugin.app,
            this.plugin
          );
          modal.open();
        })
      );
    }
  }
};

// src/card-generator.ts
var import_obsidian5 = require("obsidian");

// src/metadata-parser.ts
var MetadataParser = class {
  constructor(url, htmlText) {
    this.url = url;
    const parser = new DOMParser();
    this.htmlDoc = parser.parseFromString(htmlText, "text/html");
  }
  parse() {
    return __async(this, null, function* () {
      var _a, _b;
      const title = (_a = this.getTitle()) == null ? void 0 : _a.replace(/\r\n|\n|\r/g, "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').trim();
      if (!title) return;
      const description = (_b = this.getDescription()) == null ? void 0 : _b.replace(/\r\n|\n|\r/g, "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').trim();
      const { hostname } = new URL(this.url);
      const favicon = yield this.getFavicon();
      const image = yield this.getImage();
      return {
        url: this.url,
        title,
        description,
        host: hostname,
        favicon,
        image
      };
    });
  }
  getTitle() {
    var _a, _b, _c;
    const ogTitle = (_a = this.htmlDoc.querySelector("meta[property='og:title']")) == null ? void 0 : _a.getAttr("content");
    if (ogTitle) return ogTitle;
    return (_c = (_b = this.htmlDoc.querySelector("title")) == null ? void 0 : _b.textContent) != null ? _c : void 0;
  }
  getDescription() {
    var _a, _b, _c;
    const ogDesc = (_a = this.htmlDoc.querySelector("meta[property='og:description']")) == null ? void 0 : _a.getAttr("content");
    if (ogDesc) return ogDesc;
    return (_c = (_b = this.htmlDoc.querySelector("meta[name='description']")) == null ? void 0 : _b.getAttr("content")) != null ? _c : void 0;
  }
  getFavicon() {
    return __async(this, null, function* () {
      var _a;
      const href = (_a = this.htmlDoc.querySelector("link[rel='icon']")) == null ? void 0 : _a.getAttr("href");
      if (href) return this.resolveUrlDual(href);
      return void 0;
    });
  }
  getImage() {
    return __async(this, null, function* () {
      var _a;
      const content = (_a = this.htmlDoc.querySelector("meta[property='og:image']")) == null ? void 0 : _a.getAttr("content");
      if (content) return this.resolveUrlDual(content);
      return void 0;
    });
  }
  resolveUrl(imageUrl) {
    if (imageUrl.startsWith("//")) {
      return `https:${imageUrl}`;
    }
    if (imageUrl.startsWith("/")) {
      const { hostname } = new URL(this.url);
      return `https://${hostname}${imageUrl}`;
    }
    return imageUrl;
  }
  resolveUrlDual(url) {
    if (!url.startsWith("//")) return Promise.resolve(this.resolveUrl(url));
    const httpsUrl = `https:${url}`;
    const httpUrl = `http:${url}`;
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => resolve(httpsUrl);
      img.onerror = () => {
        const img2 = new Image();
        img2.onload = () => resolve(httpUrl);
        img2.onerror = () => resolve(httpsUrl);
        img2.src = httpUrl;
      };
      img.src = httpsUrl;
    });
  }
};

// src/utils.ts
var urlRegex = /^(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})$/i;
var lineUrlRegex = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
var linkRegex = /^\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)$/i;
var linkLineRegex = /\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)/gi;
var imageRegex = /\.(gif|jpe?g|tiff?|png|webp|bmp|tga|psd|ai)$/i;
function isUrl(text) {
  return urlRegex.test(text);
}
function isImage(text) {
  return imageRegex.test(text);
}
function isLinkedUrl(text) {
  return linkRegex.test(text);
}
function extractUrlFromLink(link) {
  const match = linkRegex.exec(link);
  if (!match || match.length < 3) return "";
  return match[2];
}

// src/editor-extensions.ts
var EditorExtensions = class {
  static getSelectedText(editor) {
    if (!editor.somethingSelected()) {
      const bounds = this.getWordBoundaries(editor);
      editor.setSelection(bounds.start, bounds.end);
    }
    return editor.getSelection();
  }
  static posFromIndex(content, index) {
    const substr = content.substring(0, index);
    let line = 0;
    let offset = -1;
    let r = -1;
    for (; (r = substr.indexOf("\n", r + 1)) !== -1; line++, offset = r) ;
    offset += 1;
    const ch = index - offset;
    return { line, ch };
  }
  static isCursorInRange(cursor, match) {
    var _a;
    const start = (_a = match.index) != null ? _a : 0;
    const end = start + match[0].length;
    return start <= cursor.ch && cursor.ch <= end;
  }
  static getWordBoundaries(editor) {
    var _a, _b;
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    for (const match of lineText.matchAll(linkLineRegex)) {
      if (this.isCursorInRange(cursor, match)) {
        const startCh = (_a = match.index) != null ? _a : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    for (const match of lineText.matchAll(lineUrlRegex)) {
      if (this.isCursorInRange(cursor, match)) {
        const startCh = (_b = match.index) != null ? _b : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    return { start: cursor, end: cursor };
  }
};

// src/card-generator.ts
var CardGenerator = class {
  constructor(editor, defaultView = "card", cacheImages = false, cacheFolder = "cards4links-cache", cacheLocation = "vault-absolute", app, onCardsCreated) {
    this.editor = editor;
    this.defaultView = defaultView;
    this.cacheImages = cacheImages;
    this.cacheFolder = cacheFolder;
    this.cacheLocation = cacheLocation;
    this.app = app;
    this.onCardsCreated = onCardsCreated;
  }
  convert(url) {
    return __async(this, null, function* () {
      var _a;
      const selectedText = this.editor.getSelection();
      const placeholderId = this.randomId();
      const placeholder = `[Fetching Data#${placeholderId}](${url})`;
      this.editor.replaceSelection(placeholder);
      new import_obsidian5.Notice(t("notice.fetchingMetadata"));
      const metadata = yield this.fetchMetadata(url);
      if (metadata && this.cacheImages && metadata.image && this.app) {
        yield this.cacheImage(metadata);
      }
      const text = this.editor.getValue();
      const start = text.indexOf(placeholder);
      if (start < 0) {
        console.log(
          `Could not find placeholder "${placeholder}" in editor, bailing out; url ${url}`
        );
        return;
      }
      const end = start + placeholder.length;
      const startPos = EditorExtensions.posFromIndex(text, start);
      const endPos = EditorExtensions.posFromIndex(text, end);
      if (!metadata) {
        new import_obsidian5.Notice(t("notice.fetchFailed"));
        this.editor.replaceRange(selectedText || url, startPos, endPos);
        return;
      }
      this.editor.replaceRange(this.generateCodeBlock(metadata), startPos, endPos);
      (_a = this.onCardsCreated) == null ? void 0 : _a.call(this, 1);
    });
  }
  convertGroup(urls) {
    return __async(this, null, function* () {
      var _a;
      if (urls.length < 2) {
        new import_obsidian5.Notice(t("notice.selectTwoUrls"));
        return;
      }
      const selectedText = this.editor.getSelection();
      const placeholderId = this.randomId();
      const placeholder = `[Fetching Data#${placeholderId}](${urls.length} links)`;
      this.editor.replaceSelection(placeholder);
      new import_obsidian5.Notice(t("notice.fetchingMetadataGroup", { count: urls.length }));
      const results = yield Promise.allSettled(
        urls.map((url) => this.fetchMetadata(url))
      );
      const metadataList = [];
      for (const r of results) {
        if (r.status === "fulfilled" && r.value) {
          metadataList.push(r.value);
        }
      }
      if (metadataList.length === 0) {
        new import_obsidian5.Notice(t("notice.fetchFailedAll"));
        this.editor.replaceSelection(selectedText || urls.join("\n"));
        return;
      }
      if (this.cacheImages && this.app) {
        for (const md of metadataList) {
          if (md.image) {
            yield this.cacheImage(md);
          }
        }
      }
      const text = this.editor.getValue();
      const start = text.indexOf(placeholder);
      if (start < 0) {
        console.log(
          `Cards4Links: could not find placeholder "${placeholder}" in editor`
        );
        return;
      }
      const end = start + placeholder.length;
      const startPos = EditorExtensions.posFromIndex(text, start);
      const endPos = EditorExtensions.posFromIndex(text, end);
      this.editor.replaceRange(
        this.generateGroupCodeBlock(metadataList),
        startPos,
        endPos
      );
      (_a = this.onCardsCreated) == null ? void 0 : _a.call(this, metadataList.length);
      new import_obsidian5.Notice(t("notice.createdCarousel", { count: metadataList.length }));
    });
  }
  generateCodeBlock(md) {
    const lines = ["\n```cardlink"];
    lines.push(`url: ${md.url}`);
    lines.push(`title: "${md.title}"`);
    if (md.description) lines.push(`description: "${md.description}"`);
    if (md.host) lines.push(`host: ${md.host}`);
    if (md.favicon) lines.push(`favicon: ${md.favicon}`);
    if (md.image) lines.push(`image: ${md.image}`);
    if (md.imageLocal) lines.push(`imageLocal: ${md.imageLocal}`);
    lines.push(`watched: false`);
    lines.push(`view: ${this.defaultView}`);
    lines.push("```\n");
    return lines.join("\n");
  }
  generateGroupCodeBlock(mdList) {
    const sections = mdList.map((md) => {
      const sLines = [];
      sLines.push(`url: ${md.url}`);
      sLines.push(`title: "${md.title}"`);
      if (md.description) sLines.push(`description: "${md.description}"`);
      if (md.host) sLines.push(`host: ${md.host}`);
      if (md.favicon) sLines.push(`favicon: ${md.favicon}`);
      if (md.image) sLines.push(`image: ${md.image}`);
      if (md.imageLocal) sLines.push(`imageLocal: ${md.imageLocal}`);
      sLines.push(`watched: false`);
      sLines.push(`view: carousel`);
      return sLines.join("\n");
    });
    return "\n```cardlink\n" + sections.join("\n---\n") + "\n```\n";
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      try {
        const res = yield (0, import_obsidian5.requestUrl)({ url });
        if (res.status !== 200) {
          console.log(`Cards4Links: bad response status ${res.status}`);
          return void 0;
        }
        const parser = new MetadataParser(url, res.text);
        return yield parser.parse();
      } catch (e) {
        console.log("Cards4Links fetch error:", e);
        return void 0;
      }
    });
  }
  cacheImage(metadata) {
    return __async(this, null, function* () {
      try {
        const activeFile = this.app.workspace.getActiveFile();
        const folder = getCacheFolderPath(
          activeFile,
          this.cacheLocation,
          this.cacheFolder
        );
        yield ensureFolder(this.app, folder);
        const filename = yield hashUrl(metadata.image);
        const existing = this.app.vault.getAbstractFileByPath(
          `${folder}/${filename}`
        );
        if (!existing) {
          const buffer = yield downloadImage(metadata.image);
          yield this.app.vault.createBinary(`${folder}/${filename}`, buffer);
        }
        const file = this.app.vault.getAbstractFileByPath(
          `${folder}/${filename}`
        );
        yield addToManifest(this.app, folder, {
          filename,
          originalUrl: metadata.image,
          cachedAt: (/* @__PURE__ */ new Date()).toISOString(),
          size: file && file instanceof import_obsidian5.TFile ? file.stat.size : 0
        });
        metadata.imageLocal = `${folder}/${filename}`;
      } catch (e) {
        console.log("Cards4Links: failed to cache image", e);
      }
    });
  }
  randomId() {
    const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
    let result = "";
    for (let i = 0; i < 4; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }
};

// src/card-processor.ts
var import_obsidian6 = require("obsidian");
function createSvgIcon(viewBox, size, ...elements) {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", viewBox);
  svg.setAttribute("width", String(size));
  svg.setAttribute("height", String(size));
  for (const [tag, attrs] of elements) {
    const el = document.createElementNS("http://www.w3.org/2000/svg", tag);
    for (const [key, val] of Object.entries(attrs)) {
      el.setAttribute(key, val);
    }
    svg.appendChild(el);
  }
  return svg;
}
function detectContentType(host) {
  if (!host) return "article";
  const videoHosts = [
    "youtube.com",
    "youtu.be",
    "vimeo.com",
    "twitch.tv",
    "dailymotion.com",
    "kick.com",
    "facebook.com"
  ];
  return videoHosts.some((h) => host.includes(h)) ? "video" : "article";
}
var YamlParseError = class extends Error {
  constructor(msg) {
    super(msg);
    this.name = "YamlParseError";
  }
};
var NoRequiredParamsError = class extends Error {
  constructor(msg) {
    super(msg);
    this.name = "NoRequiredParamsError";
  }
};
var CardProcessor = class {
  constructor(app, thumbnailPosition = "right", defaultView = "card", theme = "default", cacheImages = false, cacheFolder = "cards4links-cache", cacheLocation = "vault-absolute", cacheTTL = 30) {
    this.app = app;
    this.thumbnailPosition = thumbnailPosition;
    this.defaultView = defaultView;
    this.theme = theme;
    this.cacheImages = cacheImages;
    this.cacheFolder = cacheFolder;
    this.cacheLocation = cacheLocation;
    this.cacheTTL = cacheTTL;
    this.source = "";
    this.sections = [];
  }
  run(source, el) {
    this.source = source;
    const raw = source.split(/\n-{3,}\n/).map((s) => s.trim());
    this.sections = raw.length > 1 ? raw : [source];
    if (this.sections.length <= 1) {
      try {
        const data = this.parseYaml(source);
        this.renderCard(el, data, source, 0, false);
      } catch (error) {
        el.appendChild(this.renderError(error));
      }
    } else {
      const carousel = el.createDiv({
        cls: "cards4links-carousel",
        attr: {
          role: "region",
          "aria-label": t("aria.carousel"),
          "aria-roledescription": t("aria.carouselRoledescription")
        }
      });
      const viewport = carousel.createDiv({
        cls: "cards4links-carousel-viewport",
        attr: { "aria-live": "off" }
      });
      const track = viewport.createDiv({ cls: "cards4links-carousel-track" });
      for (let i = 0; i < this.sections.length; i++) {
        const slide = track.createDiv({
          cls: "cards4links-carousel-slide",
          attr: {
            role: "group",
            "aria-roledescription": t("aria.slideRoledescription"),
            "aria-label": t("aria.slideOf", {
              current: i + 1,
              total: this.sections.length
            })
          }
        });
        try {
          const data = this.parseYaml(this.sections[i]);
          this.renderCard(slide, data, this.sections[i], i, true);
        } catch (error) {
          slide.appendChild(this.renderError(error));
        }
      }
      const dotsContainer = carousel.createDiv({
        cls: "cards4links-carousel-dots",
        attr: { role: "tablist", "aria-label": t("aria.slideNavigation") }
      });
      for (let i = 0; i < this.sections.length; i++) {
        const dot = dotsContainer.createEl("button", {
          cls: "cards4links-carousel-dot",
          attr: {
            role: "tab",
            "aria-selected": i === 0 ? "true" : "false",
            "aria-label": t("aria.goToSlide", { index: i + 1 }),
            "data-index": String(i)
          }
        });
        if (i === 0) dot.classList.add("cards4links-carousel-dot-active");
      }
      const prevBtn = carousel.createEl("button", {
        cls: "cards4links-carousel-prev",
        attr: {
          "aria-label": t("aria.previousSlide"),
          disabled: ""
        }
      });
      prevBtn.appendChild(
        createSvgIcon(
          "0 0 24 24",
          18,
          ["path", { d: "M15 18l-6-6 6-6", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }]
        )
      );
      const nextBtn = carousel.createEl("button", {
        cls: "cards4links-carousel-next",
        attr: { "aria-label": t("aria.nextSlide") }
      });
      nextBtn.appendChild(
        createSvgIcon(
          "0 0 24 24",
          18,
          ["path", { d: "M9 6l6 6-6 6", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }]
        )
      );
      this.setupCarouselNav(viewport, dotsContainer, prevBtn, nextBtn);
    }
  }
  parseYaml(source) {
    var _a;
    let yaml;
    let indent = 0;
    const normalized = source.split(/\r?\n|\r|\n/g).map(
      (line) => line.replace(/^\t+/g, (tabs) => {
        if (indent === 0) indent = tabs.length;
        return " ".repeat(tabs.length);
      })
    ).join("\n");
    try {
      yaml = (0, import_obsidian6.parseYaml)(normalized);
    } catch (error) {
      console.log("Cards4Links YAML parse error:", error);
      throw new YamlParseError(t("error.yamlParse"));
    }
    if (!yaml || !yaml.url || !yaml.title) {
      throw new NoRequiredParamsError(t("error.requiredParams"));
    }
    return {
      url: yaml.url,
      title: yaml.title,
      description: yaml.description,
      host: yaml.host,
      favicon: yaml.favicon,
      image: yaml.image,
      watched: yaml.watched === true,
      view: (_a = yaml.view) != null ? _a : "card",
      contentType: detectContentType(yaml.host)
    };
  }
  renderCard(parentEl, data, sectionSource, cardIndex, isGroup) {
    const view = isGroup ? "carousel" : data.view || "card";
    const needsUpgrade = !/^view:/m.test(sectionSource);
    const actionsBar = createDiv({ cls: "cards4links-actions-bar" });
    if (!isGroup) {
      actionsBar.classList.add("cards4links-actions-bar-float");
    }
    if (needsUpgrade) {
      const upgradeBtn = actionsBar.createEl("button", {
        cls: "cards4links-upgrade-btn clickable-icon",
        attr: { "aria-label": t("aria.addViewField") }
      });
      upgradeBtn.appendChild(
        createSvgIcon(
          "0 0 24 24",
          14,
          ["path", { d: "M5 10l7-7 7 7", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["path", { d: "M12 3v18", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
        )
      );
      upgradeBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        container.dataset.view = isGroup ? "carousel" : this.defaultView;
        const oldSource = this.source;
        const newSections = [...this.sections];
        newSections[cardIndex] = newSections[cardIndex] + `
view: ${isGroup ? "carousel" : this.defaultView}`;
        const newSource = newSections.join("\n---\n");
        this.replaceBlock(oldSource, newSource);
        this.sections = newSections;
        this.source = newSource;
        upgradeBtn.remove();
      });
    }
    if (!isGroup) {
      const viewCycle = ["card", "compact", "minimal"];
      const viewBtn = actionsBar.createEl("button", {
        cls: "cards4links-view-btn clickable-icon",
        attr: {
          "aria-label": t("aria.view", {
            view: this.localizeView(view)
          })
        }
      });
      viewBtn.appendChild(
        createSvgIcon(
          "0 0 24 24",
          14,
          ["rect", { x: "3", y: "3", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["rect", { x: "13", y: "3", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["rect", { x: "3", y: "13", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
          ["rect", { x: "13", y: "13", width: "8", height: "8", rx: "1", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
        )
      );
      viewBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const currentView = container.dataset.view || "card";
        const next = viewCycle[(viewCycle.indexOf(currentView) + 1) % viewCycle.length];
        container.dataset.view = next;
        this.updateCardBlock(cardIndex, "view", next);
      });
    }
    const label = data.contentType === "video" ? t("label.watched") : t("label.read");
    const watchToggleBtn = actionsBar.createEl("button", {
      cls: "cards4links-watch-toggle clickable-icon",
      attr: {
        "aria-label": data.watched ? t("aria.markUnread") : t("aria.markAs", { label })
      }
    });
    const checkedSvg = createSvgIcon(
      "0 0 24 24",
      14,
      ["circle", { cx: "12", cy: "12", r: "10", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
      ["path", { d: "M8 12l3 3 5-5", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
    );
    const uncheckedSvg = createSvgIcon(
      "0 0 24 24",
      14,
      ["circle", { cx: "12", cy: "12", r: "10", fill: "none", stroke: "currentColor", "stroke-width": "2" }]
    );
    watchToggleBtn.appendChild(data.watched ? checkedSvg.cloneNode(true) : uncheckedSvg.cloneNode(true));
    watchToggleBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const currentlyWatched = container.dataset.watched === "true";
      const newWatched = !currentlyWatched;
      container.dataset.watched = newWatched ? "true" : "false";
      watchToggleBtn.empty();
      watchToggleBtn.appendChild(newWatched ? checkedSvg.cloneNode(true) : uncheckedSvg.cloneNode(true));
      watchToggleBtn.setAttr(
        "aria-label",
        newWatched ? t("aria.markUnread") : t("aria.markAs", { label })
      );
      this.updateCardBlock(cardIndex, "watched", newWatched);
    });
    const container = createDiv({
      cls: "cards4links-container",
      attr: {
        "data-thumbnail": this.thumbnailPosition,
        "data-view": view,
        "data-watched": data.watched ? "true" : "false",
        "data-theme": this.theme
      }
    });
    const card = container.createEl("a", {
      cls: "cards4links-card",
      attr: { href: data.url }
    });
    const main = card.createDiv({ cls: "cards4links-main" });
    const titleRow = main.createDiv({ cls: "cards4links-title-row" });
    titleRow.createSpan({
      cls: "cards4links-title-text",
      text: data.title
    });
    if (data.description) {
      main.createDiv({
        cls: "cards4links-description",
        text: data.description
      });
    } else {
      this.createDescriptionPlaceholder(main, cardIndex);
    }
    const hostRow = main.createDiv({ cls: "cards4links-host" });
    if (data.favicon) {
      hostRow.createEl("img", {
        cls: "cards4links-favicon",
        attr: { src: data.favicon }
      });
    }
    if (data.host) {
      hostRow.createSpan({ text: data.host });
    }
    if (data.image) {
      this.renderImage(card, data, cardIndex);
    } else {
      this.createImagePlaceholder(card, cardIndex);
    }
    const copyBtn = container.createEl("button", {
      cls: "cards4links-copy-url clickable-icon",
      attr: { "aria-label": t("aria.copyUrl", { url: data.url }) }
    });
    copyBtn.appendChild(
      createSvgIcon(
        "0 0 24 24",
        16,
        ["path", { fill: "currentColor", d: "M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z" }]
      )
    );
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void navigator.clipboard.writeText(data.url);
      new import_obsidian6.Notice(t("notice.urlCopied"));
    });
    if (isGroup) {
      const wrapper = createDiv({ cls: "cards4links-card-wrapper" });
      wrapper.appendChild(actionsBar);
      wrapper.appendChild(container);
      parentEl.appendChild(wrapper);
    } else {
      parentEl.appendChild(actionsBar);
      parentEl.appendChild(container);
    }
  }
  renderImage(card, data, cardIndex) {
    const tryLocal = data.imageLocal && this.cacheImages;
    const doRender = (src) => {
      const img = card.createEl("img", {
        cls: "cards4links-thumbnail",
        attr: { src, draggable: "false" }
      });
      img.addEventListener("error", () => {
        if (tryLocal && data.image) {
          img.remove();
          doRender(data.image);
          return;
        }
        img.remove();
        this.createImagePlaceholder(card, cardIndex, data.image);
      });
    };
    if (tryLocal) {
      void resolveResourceUrl(this.app, data.imageLocal).then((url) => {
        if (url) {
          doRender(url);
          void this.checkTtl(data);
        } else if (data.image) {
          doRender(data.image);
        } else {
          this.createImagePlaceholder(card, cardIndex);
        }
      });
    } else if (data.image) {
      doRender(data.image);
    }
  }
  checkTtl(data) {
    return __async(this, null, function* () {
      if (!data.imageLocal || this.cacheTTL <= 0 || !data.image) return;
      const folder = getCacheFolderPath(
        this.app.workspace.getActiveFile(),
        this.cacheLocation,
        this.cacheFolder
      );
      const manifest = yield getManifest(this.app, folder);
      const pathParts = data.imageLocal.split("/");
      const filename = pathParts[pathParts.length - 1];
      const entry = manifest.files.find((f) => f.filename === filename);
      if (!entry) return;
      if (!isExpired(entry, this.cacheTTL)) return;
      try {
        const buffer = yield downloadImage(data.image);
        const file = this.app.vault.getAbstractFileByPath(data.imageLocal);
        if (file instanceof import_obsidian6.TFile) {
          yield this.app.vault.modifyBinary(file, buffer);
        } else {
          yield ensureFolder(this.app, folder);
          yield this.app.vault.createBinary(data.imageLocal, buffer);
        }
        const tf = this.app.vault.getAbstractFileByPath(data.imageLocal);
        yield addToManifest(this.app, folder, {
          filename,
          originalUrl: data.image,
          cachedAt: (/* @__PURE__ */ new Date()).toISOString(),
          size: tf instanceof import_obsidian6.TFile ? tf.stat.size : 0
        });
      } catch (e) {
        console.log("Cards4Links: TTL refresh failed", e);
      }
    });
  }
  createImagePlaceholder(cardEl, cardIndex, currentImageUrl) {
    const placeholder = cardEl.createDiv({ cls: "cards4links-img-placeholder" });
    const svgContainer = placeholder.createDiv({ cls: "cards4links-img-placeholder-icon" });
    svgContainer.appendChild(
      createSvgIcon(
        "0 0 24 24",
        22,
        ["rect", { x: "2", y: "2", width: "20", height: "20", rx: "2", fill: "none", stroke: "currentColor", "stroke-width": "2" }],
        ["path", { d: "M21 15l-5-5L5 21", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }],
        ["path", { d: "M17 6h6M20 3v6", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }]
      )
    );
    placeholder.createSpan({
      cls: "cards4links-img-placeholder-text",
      text: t("placeholder.setImage")
    });
    placeholder.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const modal = new ImagePickerModal(
        this.app,
        currentImageUrl,
        (newUrl) => {
          this.updateCardBlock(cardIndex, "image", newUrl);
        }
      );
      modal.open();
    });
  }
  createDescriptionPlaceholder(main, cardIndex) {
    const placeholder = main.createDiv({ cls: "cards4links-description-placeholder" });
    placeholder.appendChild(
      createSvgIcon(
        "0 0 24 24",
        12,
        ["path", { d: "M17 3a2.828 2.828 0 114 4L7.5 20.5 2 22l1.5-5.5L17 3z", fill: "none", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }]
      )
    );
    placeholder.createSpan({
      text: t("placeholder.addDescription")
    });
    placeholder.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const modal = new DescriptionInputModal(
        this.app,
        (value) => {
          this.updateCardBlock(cardIndex, "description", value);
        }
      );
      modal.open();
    });
  }
  updateCardBlock(cardIndex, field, value) {
    const section = this.sections[cardIndex];
    const fieldRegex = new RegExp(`^${field}:.*$`, "m");
    const newSection = fieldRegex.test(section) ? section.replace(fieldRegex, `${field}: ${value}`) : section + `
${field}: ${value}`;
    const newSections = [...this.sections];
    newSections[cardIndex] = newSection;
    const newSource = newSections.join("\n---\n");
    const oldSource = this.source;
    this.replaceBlock(oldSource, newSource);
    this.sections = newSections;
    this.source = newSource;
  }
  replaceBlock(oldSource, newSource) {
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    if (!markdownView) {
      console.log("Cards4Links: no active MarkdownView");
      new import_obsidian6.Notice(t("notice.cannotEditReading"));
      return;
    }
    const editor = markdownView.editor;
    if (!editor) {
      console.log("Cards4Links: no editor available");
      return;
    }
    const text = editor.getValue();
    const blockRegex = /```cardlink\s*\n([\s\S]*?)```/g;
    let match;
    while ((match = blockRegex.exec(text)) !== null) {
      const blockContent = match[1];
      if (blockContent.replace(/\r\n/g, "\n").trimEnd() !== oldSource.replace(/\r\n/g, "\n").trimEnd()) continue;
      const lines = blockContent.split("\n");
      const hasPrefix = lines.some((l) => l.trim() && l.startsWith("> "));
      const finalContent = hasPrefix ? newSource.split("\n").map((l) => "> " + l).join("\n") : newSource;
      const startPos = EditorExtensions.posFromIndex(text, match.index);
      const endPos = EditorExtensions.posFromIndex(
        text,
        match.index + match[0].length
      );
      try {
        editor.replaceRange(
          `\`\`\`cardlink
${finalContent}
\`\`\``,
          startPos,
          endPos
        );
      } catch (e) {
        console.log("Cards4Links: failed to update code block", e);
        new import_obsidian6.Notice(t("notice.errorUpdatingCard"));
      }
      break;
    }
  }
  renderError(error) {
    const container = createDiv({ cls: "cards4links-error" });
    container.setText(t("error.cardlink", { message: error.message }));
    return container;
  }
  localizeView(view) {
    switch (view) {
      case "compact":
        return t("settings.view.compact");
      case "minimal":
        return t("settings.view.minimal");
      case "carousel":
        return t("settings.view.carousel");
      default:
        return t("settings.view.card");
    }
  }
  setupCarouselNav(viewport, dotsContainer, prevBtn, nextBtn) {
    const slides = Array.from(viewport.querySelectorAll(".cards4links-carousel-slide"));
    const dots = Array.from(dotsContainer.querySelectorAll(".cards4links-carousel-dot"));
    if (slides.length === 0) return;
    const getSlideWidth = () => {
      const slide = slides[0];
      if (!slide) return 0;
      const style = getComputedStyle(viewport.parentElement);
      const gap = parseFloat(style.getPropertyValue("gap")) || 16;
      return slide.offsetWidth + gap;
    };
    const updateNav = () => {
      const scrollLeft = viewport.scrollLeft;
      const maxScroll = viewport.scrollWidth - viewport.clientWidth;
      const atStart = scrollLeft <= 1;
      const atEnd = scrollLeft >= maxScroll - 1;
      prevBtn.toggleAttribute("disabled", atStart);
      nextBtn.toggleAttribute("disabled", atEnd);
      let closestIdx = 0;
      let closestDist = Infinity;
      slides.forEach((slide, i) => {
        const dist = Math.abs(slide.offsetLeft - scrollLeft);
        if (dist < closestDist) {
          closestDist = dist;
          closestIdx = i;
        }
      });
      dots.forEach((dot, i) => {
        const isActive = i === closestIdx;
        dot.classList.toggle("cards4links-carousel-dot-active", isActive);
        dot.setAttribute("aria-selected", isActive ? "true" : "false");
      });
    };
    let scrollTimer = 0;
    viewport.addEventListener("scroll", () => {
      window.clearTimeout(scrollTimer);
      scrollTimer = window.setTimeout(updateNav, 60);
    });
    prevBtn.addEventListener("click", () => {
      void viewport.scrollBy({ left: -getSlideWidth(), behavior: "smooth" });
    });
    nextBtn.addEventListener("click", () => {
      void viewport.scrollBy({ left: getSlideWidth(), behavior: "smooth" });
    });
    dotsContainer.addEventListener("click", (e) => {
      var _a;
      const dot = e.target.closest(".cards4links-carousel-dot");
      if (!dot) return;
      const idx = parseInt((_a = dot.dataset.index) != null ? _a : "0", 10);
      const target = slides[idx];
      if (target) {
        viewport.scrollTo({ left: target.offsetLeft, behavior: "smooth" });
      }
    });
    viewport.addEventListener("keydown", (e) => {
      if (e.key === "ArrowLeft") {
        e.preventDefault();
        void viewport.scrollBy({ left: -getSlideWidth(), behavior: "smooth" });
      } else if (e.key === "ArrowRight") {
        e.preventDefault();
        void viewport.scrollBy({ left: getSlideWidth(), behavior: "smooth" });
      }
    });
    requestAnimationFrame(() => updateNav());
  }
};
var ImagePickerModal = class extends import_obsidian6.Modal {
  constructor(app, currentUrl, onSubmit) {
    super(app);
    this.currentUrl = currentUrl != null ? currentUrl : "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("cards4links-modal");
    contentEl.createEl("h2", { text: t("modal.setImageTitle") });
    let imageUrl = this.currentUrl;
    let textInput;
    new import_obsidian6.Setting(contentEl).setName(t("modal.imageUrl")).setDesc(t("modal.imageUrlDesc")).addText((text) => {
      text.setValue(imageUrl);
      text.onChange((value) => {
        imageUrl = value;
      });
      text.inputEl.focus();
      text.inputEl.select();
      textInput = text.inputEl;
    }).addExtraButton((btn) => {
      btn.setIcon("clipboard");
      btn.setTooltip(t("modal.pasteFromClipboard"));
      btn.onClick(() => __async(this, null, function* () {
        try {
          const clipboardText = yield navigator.clipboard.readText();
          if (clipboardText) {
            imageUrl = clipboardText;
            textInput.value = clipboardText;
          }
        } catch (e) {
        }
      }));
    });
    new import_obsidian6.Setting(contentEl).addButton((btn) => {
      btn.setButtonText(t("ui.save"));
      btn.setCta();
      btn.onClick(() => {
        const url = imageUrl.trim();
        if (!url) return;
        const img = new Image();
        img.onload = () => {
          this.onSubmit(url);
          this.close();
        };
        img.onerror = () => {
          new import_obsidian6.Notice(t("notice.imageLoadFailed"));
        };
        img.src = url;
      });
    }).addButton((btn) => {
      btn.setButtonText(t("ui.cancel"));
      btn.onClick(() => {
        this.close();
      });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var DescriptionInputModal = class extends import_obsidian6.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("cards4links-modal");
    contentEl.createEl("h2", { text: t("modal.setDescriptionTitle") });
    let description = "";
    new import_obsidian6.Setting(contentEl).setName(t("modal.description")).addTextArea((text) => {
      text.setValue(description);
      text.onChange((value) => {
        description = value;
      });
      text.inputEl.rows = 4;
      text.inputEl.focus();
    });
    new import_obsidian6.Setting(contentEl).addButton((btn) => {
      btn.setButtonText(t("ui.save"));
      btn.setCta();
      btn.onClick(() => {
        this.onSubmit(description);
        this.close();
      });
    }).addButton((btn) => {
      btn.setButtonText(t("ui.cancel"));
      btn.onClick(() => {
        this.close();
      });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var WELCOME_DELAY_MS = 1500;
var CARD_MILESTONES = [
  { threshold: 1, key: "milestone.1" },
  { threshold: 3, key: "milestone.3" },
  { threshold: 5, key: "milestone.5" },
  { threshold: 10, key: "milestone.10" },
  { threshold: 25, key: "milestone.25" },
  { threshold: 50, key: "milestone.50" },
  { threshold: 100, key: "milestone.100" }
];
var Cards4Links = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.onPaste = (evt, editor) => __async(this, null, function* () {
      if (!this.settings.enhanceDefaultPaste) return;
      if (!navigator.onLine) return;
      if (!evt.clipboardData) return;
      if (evt.clipboardData.files.length > 0) return;
      const clipboardText = evt.clipboardData.getData("text/plain");
      if (!clipboardText) return;
      if (!isUrl(clipboardText) || isImage(clipboardText)) return;
      evt.stopPropagation();
      evt.preventDefault();
      const generator = this.makeGenerator(editor);
      yield generator.convert(clipboardText);
    });
    this.onEditorMenu = (menu) => {
      if (!this.settings.showInMenuItem) return;
      menu.addItem((item) => {
        item.setTitle(t("command.pasteAndEnhance")).setIcon("paste").onClick(() => __async(this, null, function* () {
          const editor = this.getEditor();
          if (!editor) return;
          yield this.manualPasteAndEnhance(editor);
        }));
      });
      if (!navigator.onLine) return;
      menu.addItem((item) => {
        item.setTitle(t("command.enhanceSelected")).setIcon("link").onClick(() => {
          const editor = this.getEditor();
          if (!editor) return;
          void this.enhanceSelected(editor);
        });
      });
      menu.addItem((item) => {
        item.setTitle(t("command.createCarousel")).setIcon("gallery-horizontal-end").onClick(() => {
          const editor = this.getEditor();
          if (!editor) return;
          void this.createCarousel(editor);
        });
      });
    };
  }
  setLanguage(lang) {
    this.settings.language = lang;
    setLanguage(resolveLang(lang));
    this.registerCommands();
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      setLanguage(resolveLang(this.settings.language));
      this.registerCommands();
      if (!this.settings.welcomeShown) {
        window.setTimeout(() => {
          new import_obsidian7.Notice(t("notice.welcome"));
          this.settings.welcomeShown = true;
          void this.saveSettings();
        }, WELCOME_DELAY_MS);
      }
      this.registerMarkdownCodeBlockProcessor("cardlink", (source, el) => {
        const processor = new CardProcessor(
          this.app,
          this.settings.thumbnailPosition,
          this.settings.defaultView,
          this.settings.theme,
          this.settings.cacheImages,
          this.settings.cacheFolder,
          this.settings.cacheLocation,
          this.settings.cacheTTL
        );
        processor.run(source, el);
      });
      this.registerEvent(
        this.app.workspace.on("editor-paste", this.onPaste)
      );
      this.registerEvent(
        this.app.workspace.on("editor-menu", this.onEditorMenu)
      );
      this.addSettingTab(new Cards4LinksSettingTab(this.app, this));
    });
  }
  registerCommands() {
    this.addCommand({
      id: "paste-and-enhance",
      name: t("command.pasteAndEnhance"),
      editorCallback: (editor) => __async(this, null, function* () {
        yield this.manualPasteAndEnhance(editor);
      }),
      hotkeys: []
    });
    this.addCommand({
      id: "upgrade-old-cards",
      name: t("command.upgradeOldCards"),
      editorCallback: (editor) => {
        this.upgradeOldCards(editor);
      }
    });
    this.addCommand({
      id: "enhance-selected-url",
      name: t("command.enhanceSelected"),
      editorCheckCallback: (checking, editor) => {
        if (!navigator.onLine) return false;
        if (checking) return true;
        void this.enhanceSelected(editor);
        return;
      },
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "e" }]
    });
    this.addCommand({
      id: "create-carousel",
      name: t("command.createCarousel"),
      editorCheckCallback: (checking, editor) => {
        if (!navigator.onLine) return false;
        if (checking) return true;
        void this.createCarousel(editor);
        return;
      },
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "c" }]
    });
    this.addCommand({
      id: "open-settings",
      name: t("command.openSettings"),
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "," }],
      callback: () => {
        const setting = this.app.setting;
        setting.open();
        setting.openTabById("cards-for-links");
      }
    });
  }
  enhanceSelected(editor) {
    return __async(this, null, function* () {
      const selected = (EditorExtensions.getSelectedText(editor) || "").trim();
      const generator = this.makeGenerator(editor);
      const urls = [];
      for (const line of selected.split(/[\n ]/)) {
        if (isUrl(line)) {
          urls.push(line);
        } else if (isLinkedUrl(line)) {
          const url = extractUrlFromLink(line);
          if (url) urls.push(url);
        }
      }
      if (urls.length === 0) return;
      if (urls.length === 1) {
        yield generator.convert(urls[0]);
      } else {
        yield generator.convertGroup(urls);
      }
    });
  }
  createCarousel(editor) {
    return __async(this, null, function* () {
      const selected = (EditorExtensions.getSelectedText(editor) || "").trim();
      const generator = this.makeGenerator(editor);
      const urls = [];
      for (const line of selected.split(/[\n ]/)) {
        if (isUrl(line)) {
          urls.push(line);
        } else if (isLinkedUrl(line)) {
          const url = extractUrlFromLink(line);
          if (url) urls.push(url);
        }
      }
      if (urls.length < 2) {
        new import_obsidian7.Notice(t("notice.selectTwoUrls"));
        return;
      }
      yield generator.convertGroup(urls);
    });
  }
  manualPasteAndEnhance(editor) {
    return __async(this, null, function* () {
      const clipboardText = yield navigator.clipboard.readText();
      if (!clipboardText) return;
      if (!navigator.onLine) {
        editor.replaceSelection(clipboardText);
        return;
      }
      if (!isUrl(clipboardText) || isImage(clipboardText)) {
        editor.replaceSelection(clipboardText);
        return;
      }
      const generator = this.makeGenerator(editor);
      yield generator.convert(clipboardText);
    });
  }
  upgradeOldCards(editor) {
    const text = editor.getValue();
    const blockRegex = /```cardlink\n([\s\S]*?)```/g;
    const replacements = [];
    let match;
    while ((match = blockRegex.exec(text)) !== null) {
      const blockContent = match[1].replace(/\r/g, "");
      if (/^view:/m.test(blockContent)) continue;
      const newContent = blockContent + (blockContent.endsWith("\n") ? "" : "\n") + `view: ${this.settings.defaultView}`;
      const startPos = EditorExtensions.posFromIndex(text, match.index);
      const endPos = EditorExtensions.posFromIndex(
        text,
        match.index + match[0].length
      );
      replacements.push({
        start: startPos,
        end: endPos,
        content: `\`\`\`cardlink
${newContent}\`\`\``
      });
    }
    if (replacements.length === 0) {
      new import_obsidian7.Notice(t("notice.noOldCards"));
      return;
    }
    replacements.reverse();
    for (const r of replacements) {
      editor.replaceRange(r.content, r.start, r.end);
    }
    new import_obsidian7.Notice(t("notice.updatedCards", { count: replacements.length }));
  }
  getEditor() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
    return view == null ? void 0 : view.editor;
  }
  makeGenerator(editor) {
    return new CardGenerator(
      editor,
      this.settings.defaultView,
      this.settings.cacheImages,
      this.settings.cacheFolder,
      this.settings.cacheLocation,
      this.app,
      (count) => this.onCardsCreated(count)
    );
  }
  loadSettings() {
    return __async(this, null, function* () {
      const data = yield this.loadData();
      this.settings = Object.assign(
        {},
        DEFAULT_SETTINGS,
        data
      );
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  onCardsCreated(count) {
    this.settings.cardsCreated += count;
    const newTotal = this.settings.cardsCreated;
    for (const milestone of CARD_MILESTONES) {
      if (newTotal >= milestone.threshold && !this.settings.milestonesShown.includes(milestone.threshold)) {
        this.settings.milestonesShown.push(milestone.threshold);
        new import_obsidian7.Notice(t(milestone.key));
      }
    }
    void this.saveSettings();
  }
};
